### ISSUE TITLE
Include 32-bit and 64-bit Windows binaries with each release

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#104]
Recompile Tesseract and OpenCV for 32-bit and update build scripts to generate both binaries

**Comment by peters** [comment]
@matthill I have a bunch of changes for windows that i'm planning on contributing. I'll prepare a PR in the coming weeks. Tesseract including it's dependencies has been linked in as git submodules so you can build either from command line or visual studio with everything working out of the box. This includes both win32 and x64 (debug/release).

It also includes a powershell script that allow you to build each part of the project individually and creation of redistributable nuget packages.

I've replaced the c++/cli binding (it's not cross platform and i need it run both on windows and mono) with a managed dll using pinvoke. The required methods are now exported via `libopenalpr` 

```c
  OPENALPR_EXPORT void* alpr_initialize(char* country, char* configFile, char* runtimeDir);
  OPENALPR_EXPORT void alpr_dispose(void* instance);
  OPENALPR_EXPORT bool alpr_is_loaded(void* instance);
  OPENALPR_EXPORT char* alpr_recognize_file(void* instance, char* imageFile);
  OPENALPR_EXPORT void alpr_free_json_mem(char* ptr);
  OPENALPR_EXPORT char* alpr_recognize_array(void* instance, unsigned char* buf, int len);
  OPENALPR_EXPORT void alpr_set_default_region(void* instance, char* default_region);
  OPENALPR_EXPORT void alpr_set_detect_region(void* instance, bool detect_region);
  OPENALPR_EXPORT void alpr_set_top_n(void* instance, int top_n);
  OPENALPR_EXPORT char* alpr_get_version(void *instance);
  OPENALPR_EXPORT void alpr_recognize_stream(void* instance, char *filename, int fps, alpr_recognize_camera_stream_callback callback);
```

**Comment by matthill** [comment]
That sounds great.  Right now I just use a batch script that runs MSBuild and copies files.  It works, but it is very kludgey.

**Comment by matthill** [comment]
also, if the changes are non-trivial, you'll need to agree to the project CLA first before I can merge the code:  https://www.clahub.com/agreements/openalpr/openalpr

**Comment by peters** [comment]
CLA has been signed.

**Comment by peters** [comment]
I've added support for `base64` encoding/decoding.

```c
  OPENALPR_EXPORT char* alpr_base64_encode(unsigned char* input, int len);
  OPENALPR_EXPORT char* alpr_base64_decode(unsigned char* input, int len);
```

**Comment by peters** [comment]
Also added width, height and compression level to `alp_recognize_stream`

```c
OPENALPR_EXPORT void alpr_recognize_stream(void* instance, char *filename, int width, int height, int fps, int compressionLevel, alpr_recognize_camera_stream_callback callback);
```

**Comment by peters** [comment]
I'm also thinking but adding two new method that returns the region of interest for the detected license plate. Should improve performance when you only need to know if the frame contains a license plate or not. What do you think?

```
OPENALPR_EXPORT alpr_region_of_interest alpr_detect_license_plate(char* filename);
OPENALPR_EXPORT alpr_region_of_interest alpr_detect_license_plate(unsigned char* buf, int len);
```

**Comment by matthill** [comment]
Is the base64 stuff ALPR related?  Or is it a normal base64 conversion function?  Would you prefer use a managed function in C#?  Or is this better/faster?  Would this be used to base64 the JSON results?

What does the width/height and compression level do?  If I start processing a video with 800x600 resolution and I pass in 1280x720, what impact does it have?

The regions of interest function is a good idea, but if it just did detection (which would save time), it would probably give too many false positives.  The cascade detector frequently picks up regions that aren't plates.  Processing the plates helps figure out which ones are truly invalid (e.g., no characters found, or a few things that could be characters, but the OCR confidence was extremely low).
