### ISSUE TITLE
Postprocess pattern matching needs to support unicode

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#108]
The pattern ##@#### should match this plate: 13누5338

Right now the Regex Library (Trex) does not support unicode letter matching: \p{L}

**Comment by peters** [comment]
@matthill Can't we just target cxx11 and get `<regex>` support for free and other goodies? :)

**Comment by matthill** [comment]
That would be nice.  I am concerned about compiler support.  But, perhaps that's not really an issue.

**Comment by matthill** [comment]
One possibility: http://www.geocities.jp/kosako3/oniguruma/

**Comment by matthill** [comment]
Resolved in commit c5324258f44976d9125ff112611cc013030c1b87
