### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by vielmetti** [openalpr/openalpr#122]
I sent in a pull request for one problem (mkdir) with the Dockerfile, but I'm stumped with this second one:

```
Step 6 : RUN cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc ..
 ---> Running in abf05c6d2b2f
CMake Error: The source directory "/srv/openalpr/src" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
INFO[0002] The command [/bin/sh -c cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc ..] returned a non-zero code: 1 
```

Suggestions? Thanks!

**Comment by vielmetti** [comment]
The pull request in question is https://github.com/openalpr/openalpr/pull/121 to fix a problem with mkdir failing.

**Comment by Silex** [comment]
What is your docker version? I just tested with 1.6.2 and everything just works...

Please also paste how you call `docker build`, you probably do something wrong.

**Comment by Silex** [comment]
Here is how I build it:

``` shell
git clone git@github.com:openalpr/openalpr.git
cd openalpr
docker build -t test .
```

**Comment by Silex** [comment]
I also tested the instructions at `https://github.com/openalpr/openalpr#docker` and they work too.

**Comment by vielmetti** [comment]
Thanks for this, missed that documentation when i was trying to do this, building now and will reopen if I run into other issues.

I do want to try to build using Docker to make this work on the Raspberry Pi, but that can be another issue.

**Comment by Silex** [comment]
I'm still curious about what you did for it to fail... I tried various stuffs and couldn't reproduce.

What command did you type for the build to fail?

**Comment by vielmetti** [comment]
To build it, I copied just the Dockerfile from the distribution into another directory, and did a build from there. (That is to say, the build directory I was working from did not have a source distribution in it).

The lines if you were to change that would be

``
# Copy all data
copy . /srv/openalpr
``

where I think you'd do a `git pull` instead and build from github rather that from local sources.

**Comment by Silex** [comment]
Ah, yeah that's not how typical Dockerfile work.

**Comment by vielmetti** [comment]
Yup. (Still learning Docker!) thanks
