### ISSUE TITLE
Support for UAE (Dubai, Abu Dhabi and it's 5 other states)

### ISSUE THREAD

**Issue by patrickpereira** [openalpr/openalpr#128]
Hi Matt,

Excellent repository, super excited about it. Has anybody worked with number plates in the UAE or elsewhere in the middle east region?

Furthermore if not, any pointers/suggestions as how to capture enough data/number plates to train the OCR?

Best regards
Patrick

**Comment by matthill** [comment]
Really, it's just a matter of snapping pictures.  There's some cropped examples in this directory: https://github.com/openalpr/train-detector/tree/master/eu

The pictures just need to be legible, they don't need to be especially high-resolution.  The key is making sure that every picture is cropped at the exact same aspect ratio.

If you need more help/advice, please post to the forum:
https://groups.google.com/forum/#!forum/openalpr
