### ISSUE TITLE
Build Failed: FeatureMatcher

### ISSUE THREAD

**Issue by whopperg** [openalpr/openalpr#130]
Hi,
im honest, i dont know whats going on here...
My host is running debian 8 (jessie)

**Installed libs:**
ii  libopenalpr-data                            2.0.1-0.1                            all          Runtime data for the OpenALPR library
ii  libopenalpr-dev                             2.0.1-0.1                            amd64        Development files for the OpenALPR library
ii  libopenalpr2                                2.0.1-0.1                            amd64        Automated License Plate Recognition library (OpenALPR)

**opencv:**
ii  libopencv-core-dev:amd64                    2.4.9.1+dfsg-1+deb8u1                amd64        development files for libopencv-core
ii  libopencv-core2.4:amd64                     2.4.9.1+dfsg-1+deb8u1                amd64        computer vision core library
ii  libopencv-dev                               2.4.9.1+dfsg-1+deb8u1                amd64        development files for opencv
**(And a bunch more of opencv libs that i just not list here because it would be to much...)**

**and the tesseract libs:**
ii  libtesseract-dev                            3.03.03-1                            amd64        Development files for the tesseract command line OCR tool
ii  libtesseract3                               3.03.03-1                            amd64        Command line OCR tool

But i always get the following error by doing this:

**git clone https://github.com/openalpr/openalpr.git
cd openalpr
cp -R distros/debian ./
fakeroot debian/rules get-orig-source
sudo apt-get install debhelper git cmake quilt libopencv-dev libtesseract-dev libtesseract-dev libleptonica-dev liblog4cplus-dev libcurl3-dev uuid-dev
debuild**

[ 31%] Building CXX object openalpr/CMakeFiles/openalpr.dir/featurematcher.cpp.o
/downloads/git/openalpr/src/openalpr/featurematcher.cpp: In constructor âalpr::FeatureMatcher::FeatureMatcher(alpr::Config*)â:
/downloads/git/openalpr/src/openalpr/featurematcher.cpp:41:54: error: invalid new-expression of abstract class type âcv::FastFeatureDetectorâ
     this->detector = new FastFeatureDetector(10, true);
                                                      ^
In file included from /usr/local/include/opencv2/calib3d.hpp:48:0,
                 from /usr/local/include/opencv2/calib3d/calib3d.hpp:48,
                 from /downloads/git/openalpr/src/openalpr/featurematcher.h:23,
                 from /downloads/git/openalpr/src/openalpr/featurematcher.cpp:20:
/usr/local/include/opencv2/features2d.hpp:388:20: note:   because the following virtual functions are pure within âcv::FastFeatureDetectorâ:
 class CV_EXPORTS_W FastFeatureDetector : public Feature2D
                    ^
/usr/local/include/opencv2/features2d.hpp:401:26: note:         virtual void cv::FastFeatureDetector::setThreshold(int)
     CV_WRAP virtual void setThreshold(int threshold) = 0;
                          ^
/usr/local/include/opencv2/features2d.hpp:402:25: note:         virtual int cv::FastFeatureDetector::getThreshold() const
     CV_WRAP virtual int getThreshold() const = 0;
                         ^
/usr/local/include/opencv2/features2d.hpp:404:26: note:         virtual void cv::FastFeatureDetector::setNonmaxSuppression(bool)
     CV_WRAP virtual void setNonmaxSuppression(bool f) = 0;
                          ^
/usr/local/include/opencv2/features2d.hpp:405:26: note:         virtual bool cv::FastFeatureDetector::getNonmaxSuppression() const
     CV_WRAP virtual bool getNonmaxSuppression() const = 0;
                          ^
/usr/local/include/opencv2/features2d.hpp:407:26: note:         virtual void cv::FastFeatureDetector::setType(int)
     CV_WRAP virtual void setType(int type) = 0;
                          ^
/usr/local/include/opencv2/features2d.hpp:408:25: note:         virtual int cv::FastFeatureDetector::getType() const
     CV_WRAP virtual int getType() const = 0;
                         ^
/downloads/git/openalpr/src/openalpr/featurematcher.cpp:42:43: error: no matching function for call to âcv::BRISK::BRISK(int, int, double)â
     this->extractor = new BRISK(10, 1, 0.9);
                                           ^
/downloads/git/openalpr/src/openalpr/featurematcher.cpp:42:43: note: candidates are:
In file included from /usr/local/include/opencv2/calib3d.hpp:48:0,
                 from /usr/local/include/opencv2/calib3d/calib3d.hpp:48,
                 from /downloads/git/openalpr/src/openalpr/featurematcher.h:23,
                 from /downloads/git/openalpr/src/openalpr/featurematcher.cpp:20:
/usr/local/include/opencv2/features2d.hpp:220:20: note: cv::BRISK::BRISK()
 class CV_EXPORTS_W BRISK : public Feature2D
                    ^
/usr/local/include/opencv2/features2d.hpp:220:20: note:   candidate expects 0 arguments, 3 provided
/usr/local/include/opencv2/features2d.hpp:220:20: note: cv::BRISK::BRISK(const cv::BRISK&)
/usr/local/include/opencv2/features2d.hpp:220:20: note:   candidate expects 1 argument, 3 provided
openalpr/CMakeFiles/openalpr.dir/build.make:307: recipe for target 'openalpr/CMakeFiles/openalpr.dir/featurematcher.cpp.o' failed
make[3]: *** [openalpr/CMakeFiles/openalpr.dir/featurematcher.cpp.o] Error 1
make[3]: Leaving directory '/downloads/git/openalpr/obj-x86_64-linux-gnu'
CMakeFiles/Makefile2:515: recipe for target 'openalpr/CMakeFiles/openalpr.dir/all' failed
make[2]: *** [openalpr/CMakeFiles/openalpr.dir/all] Error 2
make[2]: Leaving directory '/downloads/git/openalpr/obj-x86_64-linux-gnu'
Makefile:137: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/downloads/git/openalpr/obj-x86_64-linux-gnu'
dh_auto_build: make -j1 returned exit code 2
debian/rules:32: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

What is going on here?

Cheers

**Comment by matthill** [comment]
It looks like you're running a different version of OpenCV than you think.  Is it possible you manually installed OpenCV (i.e., sudo make install)?  The files are in /usr/local/include/ which is not the place where the Debian distro packages would put them.  

If it's OpenCV 3.0 you haev installed, you can try this fork to see if it compiles: https://github.com/robertocarvajal/openalpr/commit/574923972e18d290ddca2a7fb1f0dc104e033c3b

I'll update the code at some point for the new version of OpenCV, but I need to wait until it gets packaged so it's easy to install.

**Comment by robertocarvajal** [comment]
beware that state detection is not supported on opencv3 yet, I'll update that branch right now so we get the latest and greatest improvements, there's been some interesting commits recently that I want to try out anyways :)

**Comment by whopperg** [comment]
Hi guys,
hm, i've installed opencv via apt-get which should be Ver. 2.4.9.1- but you are correct, there are some binaries form opencv in this directory. So any thoughts on how i could fix that?

**Comment by whopperg** [comment]
Thats it. After removing everything related opencv and reinstalled everything via apt-get, build now completed.
Closing this for now...
