### ISSUE TITLE
OpenCV 3.0 support

### ISSUE THREAD

**Issue by robertocarvajal** [openalpr/openalpr#131]
It should be possible with a small refactoring to support both versions of OpenCV, the only feature that doesn't work out of the box is the state detector, do you plan to officially support OpenCV3 in the near future?

**Comment by matthill** [comment]
I'd like to wait until there's an opencv3 package added to Ubuntu.  It makes the install process much easier for everyone.

If that takes too long, I can package it myself and include it on my deb repo.

I'm also planning on replacing the state detector with a different approach in the medium term.  So it's fine to remove it for now -- the accuracy was never good enough (barely 50% on high resolution images).  This new approach should (hopefully) be more accurate at both high and low resolution and be applicable for EU and other countries as well.

**Comment by peters** [comment]
@matthill Built openalpr using opencv 3 on Windows and performance is roughly the same in simple my benchmark. Average recognition time has increased by ~10ms on my dev machine.

**Comment by matthill** [comment]
I updated the code to support both OpenCV 2 and OpenCV 3 simultaneously.

**Comment by turowicz** [comment]
@matthill this does not work when compiling alpr myslf with `WITH_GPU_DETECTOR=ON`

Error:

```
[ 26%] Building CXX object openalpr/CMakeFiles/openalpr.dir/alpr.cpp.o
In file included from /openalpr/src/openalpr/detection/detectorfactory.h:24:0,
                 from /openalpr/src/openalpr/alpr_impl.h:33,
                 from /openalpr/src/openalpr/alpr.cpp:21:
/openalpr/src/openalpr/detection/detectorcuda.h:34:10: fatal error: opencv2/gpu/gpu.hpp: No such file or directory
 #include "opencv2/gpu/gpu.hpp"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
