### ISSUE TITLE
Some  errors when compile

### ISSUE THREAD

**Issue by baoziv587** [openalpr/openalpr#132]
[ 21%] Built target support
[ 21%] Built target video
[ 21%] Building CXX object openalpr/CMakeFiles/openalpr.dir/featurematcher.cpp.o
/Users/dave/lib/cpp/openalpr/src/openalpr/featurematcher.cpp:41:26: error: 
      allocating an object of abstract class type 'cv::FastFeatureDetector'
    this->detector = new FastFeatureDetector(10, true);
                         ^
/usr/local/include/opencv2/features2d.hpp:401:26: note: unimplemented pure
      virtual method 'setThreshold' in 'FastFeatureDetector'
    CV_WRAP virtual void setThreshold(int threshold) = 0;
                         ^
/usr/local/include/opencv2/features2d.hpp:402:25: note: unimplemented pure
      virtual method 'getThreshold' in 'FastFeatureDetector'
    CV_WRAP virtual int getThreshold() const = 0;
                        ^
/usr/local/include/opencv2/features2d.hpp:404:26: note: unimplemented pure
      virtual method 'setNonmaxSuppression' in 'FastFeatureDetector'
    CV_WRAP virtual void setNonmaxSuppression(bool f) = 0;
                         ^
/usr/local/include/opencv2/features2d.hpp:405:26: note: unimplemented pure
      virtual method 'getNonmaxSuppression' in 'FastFeatureDetector'
    CV_WRAP virtual bool getNonmaxSuppression() const = 0;
                         ^
/usr/local/include/opencv2/features2d.hpp:407:26: note: unimplemented pure
      virtual method 'setType' in 'FastFeatureDetector'
    CV_WRAP virtual void setType(int type) = 0;
                         ^
/usr/local/include/opencv2/features2d.hpp:408:25: note: unimplemented pure
      virtual method 'getType' in 'FastFeatureDetector'
    CV_WRAP virtual int getType() const = 0;
                        ^
/Users/gaoxiang/lib/cpp/openalpr/src/openalpr/featurematcher.cpp:42:27: error: 
      no matching constructor for initialization of 'cv::BRISK'
    this->extractor = new BRISK(10, 1, 0.9);
                          ^     ~~~~~~~~~~
/usr/local/include/opencv2/features2d.hpp:220:20: note: candidate constructor
      (the implicit default constructor) not viable: requires 0 arguments, but 3
      were provided
class CV_EXPORTS_W BRISK : public Feature2D
                   ^
/usr/local/include/opencv2/features2d.hpp:220:20: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 3
      were provided
2 errors generated.
make[2]: *** [openalpr/CMakeFiles/openalpr.dir/featurematcher.cpp.o] Error 1
make[1]: *** [openalpr/CMakeFiles/openalpr.dir/all] Error 2
make: *** [all] Error 2

How can i fix  these errors?

**Comment by baoziv587** [comment]
## version: opencv3.0 .
#### Cause i  use  a  high  version opencv?

**Comment by matthill** [comment]
OpenCV 3.0 won't compile.  Try using OpenCV 2.4.9.
