### ISSUE TITLE
Extending the width of recognized plates

### ISSUE THREAD

**Issue by super-cache-money** [openalpr/openalpr#136]
The plates in my region have a font that seems perfectly recognizable with the EU config. The one problem is, the plates have a longer width. This causes the last 2 characters to be omitted from recognition sometimes. Is there a simple config setting I can change to increase the detectable width? Do I need to retrain the plate detection? 

Here's a sample plate:

![image of gauteng numberplate]
(http://i.imgur.com/ihvZFuL.jpg)

**Comment by matthill** [comment]
You can try making a copy of runtime_data/config/eu.conf and tweaking it.  You can extend the plate_Width_mm value.  I think your best option is to train a custom detector.  The plate detector is tied to the aspect ratio of the plate.  So you'll want a detector that picks out hese wider plates.
