### ISSUE TITLE
Support of WN3 and WR compiler

### ISSUE THREAD

**Issue by josepaul28** [openalpr/openalpr#149]
Hello

I need to import the static openalpr library to a WN and WR platform. But It causes a problem while compiling on WR platform.

This library currently supports both WN3 and WR compiler.?

I am working under Linux Debian (last version) and eclipse juno cdt.

Thanks in advance, best regards.
Paul Soto

**Comment by matthill** [comment]
What is WN3 and WR?  I'm not familiar with that.

**Comment by josepaul28** [comment]
Hi Matthill, thanks for your answer.

Sincerely, i don't know.. I'm working for embed the openalpr library inside the firmware of a Samsung security camera (the company in which i work is partner of Samsung Security and we have access to their API) but i have several days working on that without success because i'm getting a building error:

/opt/opensdk/opensdk-2.02/linux_devkit/bin/../lib/gcc/arm-arago-linux-gnueabi/4.5.3/../../../../arm-arago-linux-gnueabi/bin/ld: skipping incompatible /opt/opensdk//opensdk-2.02/linux_devkit/bin/../arm-arago-linux-gnueabi/usr/lib/libopenalpr-static.a when searching for -lopenalpr-static
Makefile:57: recipe for target 'bin/XLPR_wr' failed

I talk with the Samsung developers in Korea and they said:

"As our inveigation, you might import one library to WN and WR platform. It causes the problem while compiling on WR platform.
Could you check if your library supports both WN3 and WR compiler?"

I dont have idea how to check that, i am working in Debian (latest version) with Eclipse Juno CDT.

Attached you'll find images with the problem.

Regards.

![captura de pantalla de 2015-06-30 12 38 42](https://cloud.githubusercontent.com/assets/4372141/8479734/4550ae9c-209f-11e5-87fa-1d8f4a35e1f1.png)
![captura de pantalla de 2015-06-30 12 38 48](https://cloud.githubusercontent.com/assets/4372141/8479735/455cf634-209f-11e5-868c-a3f9ae79cb43.png)
![captura de pantalla de 2015-07-02 09 47 34](https://cloud.githubusercontent.com/assets/4372141/8479782/888a75bc-209f-11e5-9dca-06c1d48a6d2e.png)

**Comment by matthill** [comment]
I've compiled OpenALPR for ARM CPUs before, so it should work.  I'm not familiar with the Samsung camera SDK.  It seems more like a tools issue than an issue with OpenALPR.  I'm not sure I can be much help w/ the Samsung build tools.

**Comment by josepaul28** [comment]
And how do you compile the library for ARM CPU? i followed the steps of "The Easy Way" in https://github.com/openalpr/openalpr/wiki/Compilation-instructions-(Ubuntu-Linux). It is the same, or i need to do something different?

**Comment by matthill** [comment]
There was no package for OpenCV built for ARM on Ubuntu 14.04, so I had to compile that manually.  Otherwise, the compile is the same.  There's nothing special about OpenALPR code that would prevent it from compiling on ARM.  It's just C++98.
