### ISSUE TITLE
Stack around the variable 'ctype' was corrupted.

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#154]
@matthill ,

Toolset: Visual Studio 2013 x64

I'm experiencing a "Run-Time Check Failure 2" when running the debug build of OpenALPR. This does not happen in the release build. I've done some investigation and the problem is located at:

https://github.com/openalpr/openalpr/blob/6308048d84c5dcee4d5135da9cb2f44e8e68eb38/src/openalpr/postprocess/regexrule.cpp#L78

https://github.com/openalpr/openalpr/blob/6308048d84c5dcee4d5135da9cb2f44e8e68eb38/src/openalpr/postprocess/regexrule.cpp#L82

If you change the double backward slash to a single forward slash (`\\p` -> `\p`), it works.

Attached screenshot:

![image](https://cloud.githubusercontent.com/assets/869/8546550/0c6c76ec-24b9-11e5-8cc4-3f1a3390c035.png)

**Comment by peters** [comment]
This patch allows me to develop in debug mode: https://gist.github.com/peters/8dd900ab8a8e5af17aa3

**Comment by peters** [comment]
@matthill Is the [commit](https://github.com/openalpr/openalpr/commit/51bc9fb8d1505ffae4427075eaced2e12597f4ad) related to this issue?

**Comment by peters** [comment]
@matthill Could [r2](https://github.com/google/re2) replace oniguruma ? It supports unicode https://github.com/google/re2/wiki/Syntax

**Comment by matthill** [comment]
I looked at it when I was researching options.  However, this made me disqualify it:

    No attempt has been made to make RE2 compile on Windows, but if anyone would like to try, patches would be welcomed.

Onigurama required some patches to run on Windows, too.  So maybe re2 would have been the better choice.  I've used it on a different project and it worked great.

**Comment by peters** [comment]
Issue is now solved since the regex engine has been replaced by RE2.
