### ISSUE TITLE
How can I get the .xml file in /runtime_data/region for my country？

### ISSUE THREAD

**Issue by maxwellxxx** [openalpr/openalpr#159]
Hello, I have got the traineddata from a TTF Font, but an error "--(!)Error loading CPU classifier" returned when I run alpr. So, how can I get the xml file in /runtime_data/region for my country？Thanks!

**Comment by almendieta** [comment]
I wonder same question that maxwellxxx over there in 2015, but now in 2023. How can I get trained data to my country??
