### ISSUE TITLE
Compile issue with Visual Studio 2015 rtm

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#171]
I'm unable to compile openalpr with visual studio 2015 rtm because timespec has been included in `<time.h>`. I made some changes just to get it to compile, but i'm unsure if this correct way.

Patch: https://gist.github.com/peters/6bd5d4102fa0d5e28138

/cc @matthill

**Comment by matthill** [comment]
Not sure -- I applied your fixes (which allows it to compile).  I'll need to verify that all the timing debug output (i.e., nanosecond vs microsecond) values look right.

**Comment by peters** [comment]
:+1:
