### ISSUE TITLE
Exception thrown when a region of interest is greater than image dimensions

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#174]
If you attempt to call `recognize` when a region of interest is greater than source image dimensions an exception is thrown.

![image](https://cloud.githubusercontent.com/assets/869/9135597/91ecec3e-3d0f-11e5-9568-7aa9da2a0341.png)

**Repo**

1. Find an image that contains a license plate
2. Specify a region of interest that has width + 1
3. Blows up

```
std::vector<AlprRegionOfInterest> rois;
rois.push_back(AlprRegionOfInterest(0, 0, IMAGE_WIDTH, IMAGE_HEIGHT));
alpr.recognize(srcImage, rois);
```

**Comment by vladimirr0708982** [comment]
I think this will be better approach 
where ROI can be sent up in config file.. ( 4 coordinates of image... ) 
in that case resolutions on image can be bigger because on step before image can be "crop" and only in this area to fine plates...

**Comment by matthill** [comment]
This patch should resolve this issue.  

Vladimir what you're suggesting may be possible with clever use of the "prewarp" config variable (using the calibration utility).  You can pan/zoom to an area that you want to be analyzed.  All the data outside of this region would be ignored.
