### ISSUE TITLE
recognizeFullDetails is not thread-safe

### ISSUE THREAD

**Issue by peters** [openalpr/openalpr#178]
Ensure that all calls to `AlprImpl::recognizeFullDetails` are thread-safe.

**Comment by matthill** [comment]
I've had success running separate instances of OpenALPR on different threads.  I've tried to run the same instance of OpenALPR on separate threads, but there were segfault issues within Tesseract.

**Comment by peters** [comment]
> I've had success running separate instances of OpenALPR on different threads.

Yes, i'm doing the same thing :+1:. But maybe you should update the documentation that calling recognize is not thread safe?
