### ISSUE TITLE
Failed to open stream

### ISSUE THREAD

**Issue by onno182** [openalpr/openalpr#181]
Camera type is Foscam 960P.

Unfortunately both alprd and alpr are  unable to read the stream.

Have tried the following stream types, all of which work in browser / vlc:

stream = http://10.25.0.31:80/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=onno&pwd=secret
stream = http://10.25.0.31/cgi-bin/CGIProxy.fcgi?cmd=snapPicture&usr=onno&pwd=secret
stream = rtsp://onno:secret@10.25.0.31:80/videoSub

All return the following:

 alprd -f
INFO - Running OpenALPR daemon in the foreground.
INFO - Using: /etc/openalpr/alprd.conf for daemon configuration
INFO - Using: /var/lib/openalpr/plateimages/ for storing valid plate images
INFO - country: eu -- config file: /etc/openalpr/openalpr.conf
INFO - Stream 1: http://10.25.0.31:80/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=onno&pwd=secret
Config file location provided via API
OpenALPR Initialization Time: 522.239ms.
INFO - Starting camera 1
INFO - Video stream connecting...
WARN - Stream http://10.25.0.31:80/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=onno&pwd=secret&openalprfiletype=file.mjpg failed to open.

Debug also displays nothing.

Im out of ideas...

**Comment by matthill** [comment]
Does this URL open in VLC?
http://10.25.0.31:80/cgi-bin/CGIStream.cgi?cmd=GetMJStream&usr=onno&pwd=secret&openalprfiletype=file.mjpg

**Comment by onno182** [comment]
The problem had to do with OpenCV not being compiled with all the neccesary dependencies.  Unfortunately there is no error message to point to this.

**Comment by matthill** [comment]
Thanks for letting me know.  The video stream download is being reworked to not rely on OpenCV in the future.  It should be more stable and verbose when there are errors.

**Comment by aurelihein** [comment]
It could have been really cool to know what are those dependencies that were missing, I cannot find the opencv dependencies needed for openalpr
