### ISSUE TITLE
Tesseract 3.04 support

### ISSUE THREAD

**Issue by bosmart** [openalpr/openalpr#190]
OpenALPR builds and runs with Tesseract 3.04 but it fails to recognise licence plates ("no licence plates found") in an image, where it works fine with Tesseract 3.03rc1.

**Comment by matthill** [comment]
Tesseract changed their training data format in 3.04, so all the languages need to get retrained.  OpenALPR seems to work fine with it, assuming the language data is also trained on 3.04.  

I plan to move to Tesseract 3.04 probably with the next long term Ubuntu release (April 2016).  As far as I can tell there's no difference in speed or accuracy.
