### ISSUE TITLE
No Output - Mac

### ISSUE THREAD

**Issue by vivekparekh8** [openalpr/openalpr#192]
no license plates found - Mac

**Comment by matthill** [comment]
That doesn't necessarily mean it's a bug, it could just be that OpenALPR didn't find a plate in the image.  Can you provide more information?

**Comment by vivekparekh8** [comment]
there is license plate in the image. I downloaded it from the openalpr demo page.
The whole setup was ok. alpr command is working properly.

**Comment by matthill** [comment]
If something was wrong with the software, I would not expect that output.  The "No license plates found" message will only happen if it went through all the logic and determined that there was not a license plate in the image.

Have you modified the openalpr.conf file, or is it the default?  Can you think of anything else that might have be abnormal?

**Comment by vivekparekh8** [comment]
yes I haven't change the conf file

**Comment by vivekparekh8** [comment]
It is default

**Comment by matthill** [comment]
Thank you for reporting this issue, however I have to close it due to lack of information.  I ran the compile on my Mac and everything worked fine.  Without any more information about the problem, there's nothing I can do.

**Comment by vismayaps** [comment]
How to compile openalpr on mac ?

**Comment by danshev** [comment]
I just experienced this same issue -- no output on a Mac when using a very clear image; I suspect it's a result of some sort of overflow.

- When I used a 2 MB image, there was simply no output, despite a *very* clear plate.
- When I resized the image to 640 x 480, the plate was detected perfectly.
