### ISSUE TITLE
Char width and height in Multiline..

### ISSUE THREAD

**Issue by robeug11** [openalpr/openalpr#194]
I am working on training of multi line number plates. The multi line plate is having different char width and height for each row. The details are as follows:
First row: char width = 38, char Height = 48
Second Row: char width = 62, char Height = 92
what char width and height should be appropriate to use to make training. It would be great if anyone suggest me a little bit in details.
Thanks in advance.

**Comment by vladimirr0708982** [comment]
it's best to train bout big/small size of letter

**Comment by robeug11** [comment]
Thanks for your reply.
But what about abc.conf file in runtime_data/config where we have to mention char_height_mm and char_width_mm. Can you elaborate on this?

**Comment by matthill** [comment]
I'm working on a feature to help w/ this.  If you can upload your config, training data, and a few sample images, it would help me test.

**Comment by matthill** [comment]
This feature is now available.  In your 2-line country configuration file, you can define each text row as follows.  In this example, the top line char height is 58mm, and the bottom line char height is 82mm.
multiline = 1
char_height_mm = 58
char_width_mm = 38

char_height_mm = 82
char_width_mm = 62

**Comment by robeug11** [comment]
Thanks @matthill  for your kind support.
