### ISSUE TITLE
Python recognizeArray doesn't recognise anything

### ISSUE THREAD

**Issue by bosmart** [openalpr/openalpr#195]
There seems to be an issue with the recognizeArray function (openalprpy.cpp) as it is unable to recognise plates in a frame grabbed from a video file using OpenCV (when run from command line, alpr recognises the licence plate without any issues). Here's a code snippet:

alpr = Alpr("eu", "/etc/openalpr/openalpr.conf", "/usr/share/openalpr/runtime_data")
video = cv2.VideoCapture(fname)
ret, frame = video.read()
ret, frame = cv2.imencode("*.bmp", frame)
results = alpr.recognize_array(bytes(frame)) # results has 0 entries

**Comment by lucascdsilva** [comment]
@bosmart how do you solve this problem?

**Comment by bosmart** [comment]
@lucascdsilva 

cap = cv2.VideoCapture(fname)
ret, frame = cap.read()
ret, enc = cv2.imencode("*.bmp", frame)
results = alpr.recognize_array(bytes(bytearray(enc)))

**Comment by lucascdsilva** [comment]
@bosmart  thank you very much!!you made me very happy

**Comment by anugrahasinha** [comment]
@bosmart 
You suggestion was really helpful

> ret, enc = cv2.imencode("*.bmp", frame)
That was a real good suggestion
Also, following also helped.
>bytes(bytearray(enc)

**Comment by jjehl** [comment]
Another solution : 
ret, enc = cv2.imencode("*.jpg", frame)
results = alpr.recognize_array(enc.tobytes())

**Comment by alucard079** [comment]
Can I feed a stream?
