### ISSUE TITLE
Handle Bad images

### ISSUE THREAD

**Issue by kjlaw89** [openalpr/openalpr#196]
OpenCV Error: Assertion failed (buf.data && buf.isContinuous()) in cv::imdecode_, file C:\Users\Kevin\Documents\GitHub\node-openalpr\openalpr\windows\opencv\modules\highgui\src\loadsave.cpp, line 307

We ran into a case with our application where a bad image was passed in (empty or in some cases had HTML in them [access denied message]) and OpenALPR threw the above error. I'm not sure if I can catch it with a try/catch, but it might not hurt to catch the result on the OpenALPR side and return an error message in the results object.

**Comment by matthill** [comment]
Thanks for the bug report.

Can you upload the image that caused the problem?  Is it reproducible?  If so it would make it much easier to fix.

**Comment by matthill** [comment]
Added try/catch statements that should keep the library from crashing on most bad images.
