### ISSUE TITLE
Exclude certain characters

### ISSUE THREAD

**Issue by Brblol** [openalpr/openalpr#203]
The letter I and l is often confused. It is why the letter i is never on a GB plate. There should be a blacklist of characters for each country that should be ignored like the letter i for GB

The image below is of plate number BD15 DLO

![11](https://cloud.githubusercontent.com/assets/3162573/10126666/91c72d94-658e-11e5-8133-77f3f7f84d02.JPG)

alpr -c eu -p gb -n 15 "samples\uk cars\11.jpg"plate0: 15 results

    - BDI5DLO    confidence: 93.9794     pattern_match: 0
    - BDI5DL0    confidence: 91.5029     pattern_match: 0
    - BDI5DLD    confidence: 88.5153     pattern_match: 0
    - BDI5DLQ    confidence: 88.2559     pattern_match: 0
    - BDI5DLC    confidence: 86.3805     pattern_match: 0
    - BDISDLO    confidence: 86.275      pattern_match: 0
    - BDI5DLG    confidence: 86.0718     pattern_match: 0
    - BDI50LO    confidence: 85.8667     pattern_match: 0
    - BDISDL0    confidence: 83.7985     pattern_match: 0
    - BDI50L0    confidence: 83.3902     pattern_match: 0
    - BDISDLD    confidence: 80.8109     pattern_match: 0
    - BDISDLQ    confidence: 80.5515     pattern_match: 0
    - BDI50LD    confidence: 80.4026     pattern_match: 0
    - BDI50LQ    confidence: 80.1432     pattern_match: 0
    - BDISDLC    confidence: 78.6761     pattern_match: 0

**Comment by matthill** [comment]
Thanks for the bug report.

If you run with -n 100, one of those values (BD15DLO) would likely match the pattern...  Does that work?

In the future, I plan to add custom OCR training that is specific for GB.  I have the data, but other projects keep pushing to the front.  Once the training is done all the "I" characters would go away.

**Comment by Brblol** [comment]
Great. thanks

I have run it again with n=100 and it the right plate number is not in the results.

alpr -c eu -p gb -n 100 "samples\uk cars\11.jpg"

plate0: 96 results
    - BDI5DLO    confidence: 93.9794     pattern_match: 0
    - BDI5DL0    confidence: 91.5029     pattern_match: 0
    - BDI5DLD    confidence: 88.5153     pattern_match: 0
    - BDI5DLQ    confidence: 88.2559     pattern_match: 0
    - BDI5DLC    confidence: 86.3805     pattern_match: 0
    - BDISDLO    confidence: 86.275      pattern_match: 0
    - BDI5DLG    confidence: 86.0718     pattern_match: 0
    - BDI50LO    confidence: 85.8667     pattern_match: 0
    - B0I5DLO    confidence: 85.5264     pattern_match: 0
    - BDI5OLO    confidence: 85.1986     pattern_match: 0
    - BDI5QLO    confidence: 84.7866     pattern_match: 0
    - BDI5BLO    confidence: 84.3226     pattern_match: 0
    - BDISDL0    confidence: 83.7985     pattern_match: 0
    - BDI50L0    confidence: 83.3902     pattern_match: 0
    - B0I5DL0    confidence: 83.0498     pattern_match: 0
    - BDI5OL0    confidence: 82.7221     pattern_match: 0
    - BDI5QL0    confidence: 82.3101     pattern_match: 0
    - BDI5BL0    confidence: 81.8461     pattern_match: 0
    - BDISDLD    confidence: 80.8109     pattern_match: 0
    - BDISDLQ    confidence: 80.5515     pattern_match: 0
    - BDI50LD    confidence: 80.4026     pattern_match: 0
    - BDI50LQ    confidence: 80.1432     pattern_match: 0
    - B0I5DLD    confidence: 80.0623     pattern_match: 0
    - B0I5DLQ    confidence: 79.8029     pattern_match: 0
    - BDI5OLD    confidence: 79.7346     pattern_match: 0
    - BDI5OLQ    confidence: 79.4752     pattern_match: 0
    - BDI5QLD    confidence: 79.3225     pattern_match: 0
    - BDI5QLQ    confidence: 79.0631     pattern_match: 0
    - BDI5BLD    confidence: 78.8585     pattern_match: 0
    - BDISDLC    confidence: 78.6761     pattern_match: 0
    - BDI5BLQ    confidence: 78.5991     pattern_match: 0
    - BDISDLG    confidence: 78.3674     pattern_match: 0
    - BDI50LC    confidence: 78.2678     pattern_match: 0
    - BDIS0LO    confidence: 78.1623     pattern_match: 0
    - BDI50LG    confidence: 77.9591     pattern_match: 0
    - B0I5DLC    confidence: 77.9274     pattern_match: 0
    - B0ISDLO    confidence: 77.822      pattern_match: 0
    - B0I5DLG    confidence: 77.6188     pattern_match: 0
    - BDI5OLC    confidence: 77.5997     pattern_match: 0
    - BDISOLO    confidence: 77.4942     pattern_match: 0
    - B0I50LO    confidence: 77.4137     pattern_match: 0
    - BDI5OLG    confidence: 77.291      pattern_match: 0
    - BDI5QLC    confidence: 77.1877     pattern_match: 0
    - BDISQLO    confidence: 77.0822     pattern_match: 0
    - BDI5QLG    confidence: 76.879      pattern_match: 0
    - B0I5OLO    confidence: 76.7456     pattern_match: 0
    - BDI5BLC    confidence: 76.7237     pattern_match: 0
    - BDISBLO    confidence: 76.6182     pattern_match: 0
    - BDI5BLG    confidence: 76.415      pattern_match: 0
    - B0I5QLO    confidence: 76.3336     pattern_match: 0
    - B0I5BLO    confidence: 75.8696     pattern_match: 0
    - BDIS0L0    confidence: 75.6858     pattern_match: 0
    - B0ISDL0    confidence: 75.3455     pattern_match: 0
    - BDISOL0    confidence: 75.0177     pattern_match: 0
    - B0I50L0    confidence: 74.9371     pattern_match: 0
    - BDISQL0    confidence: 74.6057     pattern_match: 0
    - B0I5OL0    confidence: 74.2691     pattern_match: 0
    - BDISBL0    confidence: 74.1417     pattern_match: 0
    - B0I5QL0    confidence: 73.857      pattern_match: 0
    - B0I5BL0    confidence: 73.393      pattern_match: 0
    - BDIS0LD    confidence: 72.6982     pattern_match: 0
    - BDIS0LQ    confidence: 72.4388     pattern_match: 0
    - B0ISDLD    confidence: 72.3579     pattern_match: 0
    - B0ISDLQ    confidence: 72.0985     pattern_match: 0
    - BDISOLD    confidence: 72.0302     pattern_match: 0
    - B0I50LD    confidence: 71.9496     pattern_match: 0
    - BDISOLQ    confidence: 71.7708     pattern_match: 0
    - B0I50LQ    confidence: 71.6902     pattern_match: 0
    - BDISQLD    confidence: 71.6181     pattern_match: 0
    - BDISQLQ    confidence: 71.3587     pattern_match: 0
    - B0I5OLD    confidence: 71.2815     pattern_match: 0
    - BDISBLD    confidence: 71.1541     pattern_match: 0
    - B0I5OLQ    confidence: 71.0221     pattern_match: 0
    - BDISBLQ    confidence: 70.8947     pattern_match: 0
    - B0I5QLD    confidence: 70.8695     pattern_match: 0
    - B0I5QLQ    confidence: 70.6101     pattern_match: 0
    - BDIS0LC    confidence: 70.5634     pattern_match: 0
    - B0I5BLD    confidence: 70.4055     pattern_match: 0
    - BDIS0LG    confidence: 70.2547     pattern_match: 0
    - B0ISDLC    confidence: 70.223      pattern_match: 0
    - B0I5BLQ    confidence: 70.1461     pattern_match: 0
    - B0ISDLG    confidence: 69.9144     pattern_match: 0
    - BDISOLC    confidence: 69.8953     pattern_match: 0
    - B0I50LC    confidence: 69.8147     pattern_match: 0
    - BDISOLG    confidence: 69.5866     pattern_match: 0
    - B0I50LG    confidence: 69.5061     pattern_match: 0
    - BDISQLC    confidence: 69.4833     pattern_match: 0
    - BDISQLG    confidence: 69.1746     pattern_match: 0
    - B0I5OLC    confidence: 69.1467     pattern_match: 0
    - BDISBLC    confidence: 69.0193     pattern_match: 0
    - B0I5OLG    confidence: 68.838      pattern_match: 0
    - B0I5QLC    confidence: 68.7346     pattern_match: 0
    - BDISBLG    confidence: 68.7106     pattern_match: 0
    - B0I5QLG    confidence: 68.426      pattern_match: 0
    - B0I5BLC    confidence: 68.2706     pattern_match: 0
    - B0I5BLG    confidence: 67.962      pattern_match: 0

**Comment by EccentricDyslexic** [comment]
Same with O and 0, only need one of them, I'd say O looks closer to UK plates.

**Comment by matthill** [comment]
Added a GB font in this commit: ba69a50a8f30588a871818b09769a8e6358d8d89

There is no longer an "I" or "Q" character.  There is still an O, but it looks exactly like 0. 

The GB OCR training data was uploaded here: https://github.com/openalpr/train-ocr

**Comment by ionutene** [comment]
Hi there,
I want to exclude the mandatory circle from periodical technical inspection from next example:
![imag0619](https://user-images.githubusercontent.com/25953456/37138430-ae9e98a6-22b2-11e8-9b45-1b8a129c5eba.jpg)

alpr -c eu -p ro IMAG0619.jpg [ INFO:0] Initialize OpenCL runtime...
plate0: 10 results
    - DB8KIDI	 confidence: 85.549	 pattern_match: 0
    - DB8KDI	 confidence: 85.2272	 pattern_match: 0
    - DB8KID	 confidence: 85.215	 pattern_match: 0
    - 0B8KIDI	 confidence: 76.1398	 pattern_match: 0
    - 0B8KDI	 confidence: 75.818	 pattern_match: 0
    - 0B8KID	 confidence: 75.8058	 pattern_match: 0
    - DB8KI0I	 confidence: 75.787	 pattern_match: 0
    - DB8K0I	 confidence: 75.4652	 pattern_match: 0
    - DB8KI0	 confidence: 75.453	 pattern_match: 0
    - DBBKIDI	 confidence: 74.565	 pattern_match: 0

It should be DB28KID and "2" is not seen due to that circle.

Thank you in advance
