### ISSUE TITLE
Latest commit change result with attached image...

### ISSUE THREAD

**Issue by xittos** [openalpr/openalpr#205]
With the latest commit (1 oct 2015), I can't get the correct pattern (matched) in the first 10 plate detected by openalpr whereas before it was the second! How can I get the previous performance back? Thanks. 

Plate detected now:
    - EL78OKCI   confidence: 90.0682     pattern_match: 0
    - EL780KCI   confidence: 87.826      pattern_match: 0
    - EL78DKCI   confidence: 84.8085     pattern_match: 0
    - EL78QKCI   confidence: 84.7267     pattern_match: 0
    - EL78GKCI   confidence: 83.9228     pattern_match: 0
    - EL78OKC    confidence: 83.9225     pattern_match: 0
    - EL7BOKCI   confidence: 82.9933     pattern_match: 0
    - EL78OKCE   confidence: 82.9793     pattern_match: 0
    - EL78BKCI   confidence: 82.8692     pattern_match: 0
    - EL78CKCI   confidence: 81.9152     pattern_match: 0

Plate detected before (last commit 25 sep 2015):
    - EL78OKC    confidence: 90.1471     pattern_match: 0
    - EL780KC    confidence: 87.8107     pattern_match: 1
    - EL78OKCE   confidence: 86.7006     pattern_match: 0
    - EL78OKC5   confidence: 85.0456     pattern_match: 0
    - EL78DKC    confidence: 84.6664     pattern_match: 0
    - EL78OKCG   confidence: 84.6644     pattern_match: 0
    - EL78OKCF   confidence: 84.652      pattern_match: 0
    - EL78QKC    confidence: 84.5812     pattern_match: 0
    - EL780KCE   confidence: 84.3641     pattern_match: 0
    - EL78GKC    confidence: 83.7435     pattern_match: 0

Command used: ./alpr --config config/openalpr.conf -c eu -p it it*.jpg

![it17611](https://cloud.githubusercontent.com/assets/8083995/10215013/1c1a8626-681e-11e5-8b11-943a31cef0f5.jpg)

**Comment by matthill** [comment]
Overall accuracy has improved slightly between those commits.  Just due to randomness results will be different.  You can always continue using the old code.  If you alter the image slightly and imperceptibly, in the case where the results are correct, you can do it such that the results don't show up in the top 10.

Try using the new option "must_match_pattern" and increasing your top_n to 40 or so.
