### ISSUE TITLE
JSON garbage results

### ISSUE THREAD

**Issue by edwardscdr** [openalpr/openalpr#206]
I have openalpr running on Raspberry Pi 2 Jessie and I am getting garbage epoch_time, img_width and img_height json results. Otherwise it is working fine.

alpr -c eu -p gb -j /home/pi/Pictures/motion/9.jpg
```
{"version":2,"data_type":"alpr_results","epoch_time":339222727560790080,"img_width":1995554816,"img_height":1995554192,"processing_time_ms":2480.809814,"regions_of_interest":[],"results":[{"plate":"WF60XHX","confidence":91.550560,"matches_template":1,"plate_index":0,"region":"gb","region_confidence":0,"processing_time_ms":466.539795,"requested_topn":1960213956,"coordinates":[{"x":546,"y":378},{"x":625,"y":373},{"x":624,"y":394},{"x":546,"y":399}],"candidates":[{"plate":"WF60XHX","confidence":91.550560,"matches_template":1},{"plate":"F60XHX","confidence":90.266731,"matches_template":0},{"plate":"HF60XHX","confidence":89.031929,"matches_template":1},{"plate":"WF6OXHX","confidence":88.450645,"matches_template":0},{"plate":"F6OXHX","confidence":87.166809,"matches_template":0},{"plate":"NF60XHX","confidence":86.304214,"matches_template":1},{"plate":"HF6OXHX","confidence":85.932007,"matches_template":0},{"plate":"WF6DXHX","confidence":85.472466,"matches_template":0},{"plate":"WF6QXHX","confidence":85.370323,"matches_template":0},{"plate":"RF60XHX","confidence":85.019745,"matches_template":1}]}]}`
```

This image is actually 1000x727px. The python binding is also giving me similar but different results for same image:

```
u'epoch_time': 281324652920796L,
u'img_height': 65503,
u'img_width': 65502
```

Thanks

**Comment by matthill** [comment]
Thanks for the report.  I'm not seeing this issue on my RPi2...

What output do you get when you run the commands 
  - uname -a
  - cat /etc/*release

My output is:
Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by matthill** [comment]
Also, what version of OpenALPR is this?  Is this the latest code or release 2.1.0?

**Comment by edwardscdr** [comment]
```
Linux raspberrypi 4.1.8-v7+ #818 SMP PREEMPT Tue Sep 29 01:40:47 BST 2015 armv7l GNU/Linux

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

This is with latest openalpr from github cloned about 3 days ago. It could be something to do with the new jessie raspbian?

**Comment by matthill** [comment]
Thanks, Edward.  Yes, perhaps.  I'll try upgrading my hardware to see if I can reproduce.

**Comment by matthill** [comment]
Thanks again for the report.  I was able to reproduce it and fix it.
