### ISSUE TITLE
Error while installing on Ubuntu 15.04...

### ISSUE THREAD

**Issue by robeug11** [openalpr/openalpr#208]
I am not able to install openalpr on Ubuntu 15.4 system. It's giving following error:

sudo apt-get install openalpr openalpr-daemon
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openalpr : Depends: libopenalpr2 (= 2.1.108-0.1) but it is not going to be installed
            Depends: libavcodec54 (>= 6:9.1-1) but it is not installable or
                     libavcodec-extra-54 (>= 6:9.18) but it is not installable
            Depends: libavformat54 (>= 6:9.1-1) but it is not installable
            Depends: libavutil52 (>= 6:9.1-1) but it is not installable
            Depends: libswscale2 (>= 6:9.1-1) but it is not installable
 openalpr-daemon : Depends: libopenalpr2 (= 2.1.108-0.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Have anyone faced such situation before? Thanks in advance!

**Comment by matthill** [comment]
The precompiled binaries are for Ubuntu 14.04.  We just do binaries for LTS versions, not the intermediate Ubuntu releases.  You can compile them yourself though following these instructions:
https://github.com/openalpr/openalpr/wiki/Compilation-instructions-(Ubuntu-Linux)#the-easy-way
