### ISSUE TITLE
OpenALPR in Python/Ubuntu

### ISSUE THREAD

**Issue by jerome-white** [openalpr/openalpr#210]
I'm unable to get OpenALPR to work within Python ("ImportError: No module named 'openalpr'"). I'm using Ubuntu 14.04 and have followed all instructions for apt-get installation. As a first step, I'm unable to find the src/bindings directory.

Is it possible to provide more detailed description of making Python modules from the described apt-get installation instructions?

**Comment by matthill** [comment]
Try:

sudo apt-get update && sudo apt-get install python-openalpr

**Comment by EccentricDyslexic** [comment]
Hi all, is this the best way to update my alprd I have running on my Ubuntu ?  I'd love the better accuracy for uk plates.  I suspect I will have to make some changes to the configure files?

Many thanks,

Steve

**Comment by matthill** [comment]
Did you install via apt-get or did you compile it yourself?

If the former:
sudo apt-get update && sudo apt-get upgrade

If the latter, you can recompile and run make install again to overwrite all the files with the new version.

**Comment by EccentricDyslexic** [comment]
Thanks Matt, i only dip into python occasionally, so forget to do the simplest of things, like cding into lower directories, i had to Google it all over again!

The upgrade went well, do i need to make any changes to get the UK training data used?

Cheers

Steve

**Comment by matthill** [comment]
The UK training data should be part of the updated package.  The country code is "gb".  Use alpr -c gb [image file] to test.

**Comment by jerome-white** [comment]
Thanks @matthill Those instructions got it working for Python 2 -- is there an equivalent for Python 3?

**Comment by EccentricDyslexic** [comment]
do i set gb instead of eu in conf file for alprd?

thanks!

Steve

**Comment by matthill** [comment]
@EccentricDyslexic Yes, that's correct.  The GB data uses the EU detector and OCR data trained from UK plates
@jerome-white The Python integration is installed for Python 2 via that deb package.  I haven't done any work or testing to integrate it with Python 3, although I imagine the code wouldn't be too much different.
