### ISSUE TITLE
build 2.2.0 .NET

### ISSUE THREAD

**Issue by favy87** [openalpr/openalpr#214]
In the x64 version I get the following error when processing an image in .NET
Additional information: Could not load file or assembly 'openalpr-net, Version = 2.2.0.0, Culture = neutral, PublicKeyToken = null' or one of its dependencies. An attempt was made to load a program with an incorrect format.

In the x32 version it gives me an error of assembling the DLL

The DLL that I have are:
liblept170.dll
openalpr.conf
openalpr.dll
openalprjni.dll
openalpr-net.dll
openalprpy.dll
opencv_ffmpeg300.dll
opencv_world300.dll

**Comment by favy87** [comment]
to run anpr.exe tells me that I need the following dll:
MSVCP140.DLL
VCRUNTIME140.DLL

**Comment by favy87** [comment]
Installing failure vcredist.x86.exe missing dll is solved. But I still can not process the image from .NET. I have the same problems as in the first message.

**Comment by matthill** [comment]
This is almost always caused by a 32/64 bit mismatch.  Most people see this when they compile on a 64-bit machine, using the 64-bit DLLs, but are compiling their .NET program in 32-bit mode.  Here's a SO article with more discussion:

http://stackoverflow.com/questions/11370344/could-not-load-file-or-assembly-an-attempt-was-made-to-load-a-program-with-a

**Comment by favy87** [comment]
OK. It works now. He was crossing the dll

Thk

**Comment by sternleyh** [comment]
is there no documentation for openalpr-net RecognizeFromVideo?

**Comment by AntonioLuizTadeu** [comment]
Colegas boa noite!

Estou com um problema na hora de abrir uma imagem. 
Segue: 
Informação adicional: Não foi possível carregar arquivo ou assembléia 'openalpr-net, Version = 2.3.0.0, Cultura = neutro, PublicKeyToken = null' ou uma das suas dependências. Foi feito uma tentativa de carregar uma 
chamada: processImageFile (openFileDialog.FileName);

Estou usando uma Versão: openalpr-2.3.0 \ openalpr-2.3.0 \ src \ bindings \ csharp.

Se puderem ajudar agradeço.
