### ISSUE TITLE
Add option to skip conversion to grayscale

### ISSUE THREAD

**Issue by nglinh** [openalpr/openalpr#216]
I'm working off a Raspberry pi with the pi camera module. I'm capturing images in grayscale to improve th e fps. However openalpr automatically convert color to gray scale, which caused problem (since the image is already in grayscale). There should be a detection or some step to skip the conversion if the image is already in gray.

Thanks

**Comment by matthill** [comment]
Thanks for the report.  What error message are you seeing?  Can you upload a sample image where the problem occurs?

I tried to reproduce it with a simple grayscale jpg image, but it seemed to recognize properly.  Maybe it's specific to certain image formats...

**Comment by nglinh** [comment]
I'm getting this:

OpenCV Error: Assertion failed (scn == 3 || scn == 4) in cvtColor, file /home/pi/opencv/modules/imgproc/src/color.cpp, line 7564
*** Error in `./trafficpi': double free or corruption (!prev): 0x6df0d798 ***

If I run it through cv::cvtColor(frame, frame, CV_GRAY2BGR); everything runs fine.

**Comment by nglinh** [comment]
Here's how I'm using openalpr:

alpr::AlprResults results = openalpr.recognize(frame.data, frame.elemSize(), frame.size().width, frame.size().height, masks);
