### ISSUE TITLE
problem with compilation: test_api

### ISSUE THREAD

**Issue by Piotr-23** [openalpr/openalpr#218]
after pulling the latest commit, the make stops at [ 67%] Building CXX object tests/CMakeFiles/unittests.dir/test_api.cpp.o

[ 67%] Building CXX object tests/CMakeFiles/unittests.dir/test_api.cpp.o
In file included from /home/piotr/_download/openalpr_20151026/openalpr/src/tests/test_api.cpp:13:0:
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:812:17: error: ‘nullptr_t’ in namespace ‘std’ does not name a type
     inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                 ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:58: error: ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare’ conflicts with a previous declaration
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                          ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:927:44: note: previous declaration ‘namespace Catch::Internal { }::compare’
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:53: error: ‘nullptr_t’ is not a member of ‘std’
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                     ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:70: error: expected primary-expression before ‘*’ token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                      ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:72: error: ‘rhs’ was not declared in this scope
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                        ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:76: error: expression list treated as compound expression in initializer [-fpermissive]
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                            ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:44: warning: variable templates only available with -std=c++14 or -std=gnu++14
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                            ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:933:78: error: expected ‘;’ before ‘{’ token
     template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                                              ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:936:66: error: ‘std::nullptr_t’ has not been declared
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                                  ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:936:44: error: redefinition of ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)’
     template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                            ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:927:44: note: ‘template<Catch::Internal::Operator Op, class T> bool Catch::Internal::compare(T*, int)’ previously declared here
     template<Operator Op, typename T> bool compare( T* lhs, int rhs ) {
                                            ^
In file included from /home/piotr/_download/openalpr_20151026/openalpr/src/tests/test_api.cpp:13:0:
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:1183:38: error: ‘std::__cxx11::string Catch::toString’ redeclared as different kind of symbol
 std::string toString( std::nullptr_t );
                                      ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:1180:13: note: previous declaration ‘std::__cxx11::string Catch::toString(unsigned char)’
 std::string toString( unsigned char value );
             ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:1183:23: error: ‘nullptr_t’ is not a member of ‘std’
 std::string toString( std::nullptr_t );
                       ^
In file included from /home/piotr/_download/openalpr_20151026/openalpr/src/tests/test_api.cpp:13:0:
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:6977:38: error: ‘std::__cxx11::string Catch::toString’ redeclared as different kind of symbol
 std::string toString( std::nullptr_t ) {
                                      ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:6972:13: note: previous declaration ‘std::__cxx11::string Catch::toString(unsigned char)’
 std::string toString( unsigned char value ) {
             ^
/home/piotr/_download/openalpr_20151026/openalpr/src/tests/catch.hpp:6977:23: error: ‘nullptr_t’ is not a member of ‘std’
 std::string toString( std::nullptr_t ) {
                       ^
tests/CMakeFiles/unittests.dir/build.make:54: recipe for target 'tests/CMakeFiles/unittests.dir/test_api.cpp.o' failed
make[2]: *** [tests/CMakeFiles/unittests.dir/test_api.cpp.o] Error 1
CMakeFiles/Makefile2:468: recipe for target 'tests/CMakeFiles/unittests.dir/all' failed
make[1]: *** [tests/CMakeFiles/unittests.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by zachary822** [comment]
Same.

**Comment by junwatu** [comment]
I have the same issue on fedora 23

**Comment by Piotr-23** [comment]
I solved that:
https://groups.google.com/forum/#!topic/openalpr/Nl2dhXzjaC0
----
In case someone wants to compile.
As suggested here:
https://github.com/philsquared/Catch/issues/424
one needs to add "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")" to CMakeLists.txt

Voila, problem solved | P
