### ISSUE TITLE
plate detection fail???

### ISSUE THREAD

**Issue by radioman** [openalpr/openalpr#221]
somehow it doesn't recognize this, no results in http://www.openalpr.com/demo.html

?? 
![xxf](https://cloud.githubusercontent.com/assets/709019/10974555/61abe098-83eb-11e5-9549-69528a1b6be5.jpg)

**Comment by matthill** [comment]
That plate is unusual looking, compared to other European plates.  It's not as wide as standard EU single-line plates.  It would likely need its own detector.  More info on doing that training is here: https://github.com/openalpr/train-detector
