### ISSUE TITLE
Error LNK1104: cannot open file '..\..\..\..libtesseract303-static-debug.lib'

### ISSUE THREAD

**Issue by vanloc0301** [openalpr/openalpr#239]
I built project C#, add the opencv2 folder to `Include directory` in `VC++ directories` and `openalpr-net.dll` to my project.

I build project and show error:
Error LNK1104: cannot open file '..\..\..\..\windows\build\dist\2.1.0\v120\Debug\Win32\libtesseract303-static-debug.lib'

I continue have an error like this every building project.

How to fix this?

**Comment by matthill** [comment]
Does the file exist?  It may be better to post the issue on the Windows build project
https://github.com/peters/openalpr-windows
