### ISSUE TITLE
Where OPENCV_DIR and SAMPLE_CREATE folder in windows?

### ISSUE THREAD

**Issue by vanloc0301** [openalpr/openalpr#241]
Can't I find any folder like alpr/librabies/opencv/bin on the opencv folder or alpr project?

I want config this to train data. It is a component of prep.py.

And I don't know WIDTH and HEIGHT are the dimension of the picture to training or anything? Can anyone explain to me?

Thanks for that.

**Comment by matthill** [comment]
You can download OpenCV from their website:
http://opencv.org/

The width/height for detector training should be the same aspect ratio of your plate images, but generally much smaller.  Here's a good resource on cascade detector training:
http://note.sonots.com/SciSoftware/haartraining.html
