### ISSUE TITLE
OpenALPR fails to recognize single-channel IplImage

### ISSUE THREAD

**Issue by ssmelov** [openalpr/openalpr#247]
When passing a single-channel IplImage to alpr::recognize() method it fails because it expects to have a 3-channel image as a source and tries to convert BGR image into grayscale.

The program fails at LicensePlateCandidate::recognize() method on the following line:

    cv::cvtColor(pipeline_data->color_deskewed, pipeline_data->crop_gray, CV_BGR2GRAY);

Would it be convinient to add a check for number of channels before invocation of cvtColor method in order to prevent this type of issue?

```
if (pipeline_data->color_deskewed.channels() > 1)
{
  cv::cvtColor(pipeline_data->color_deskewed, pipeline_data->crop_gray, CV_BGR2GRAY);
}
```

If you are okay with this change I can add a pull request.

**Comment by matthill** [comment]
Yes, definitely.  I thought the library already did this -- but perhaps there was a regression.

**Comment by matthill** [comment]
I tried a grayscale image and it works fine.  I'm not able to reproduce...  Can you upload an image that fails?

![graycar](https://cloud.githubusercontent.com/assets/508260/12222289/1f913108-b786-11e5-8e98-d731e1685411.jpg)

**Comment by ssmelov** [comment]
Hello Matt,

I'm sorry it took me that long to come back to you with some details about this issue.
This issue occurs only when you pass 1-channel(grayscale) IplImage or cv::Mat to the recognize method of alpr.

Here is a short example you can use to reproduce this issue:

```
cv::Mat matImage = cv::imread("C:\\grayscale.jpg", cv::IMREAD_GRAYSCALE);
 
std::vector<alpr::AlprRegionOfInterest> regionsOfInterest;
regionsOfInterest.push_back(alpr::AlprRegionOfInterest(0, 0, matImage.cols, matImage.rows));
 
alpr::AlprResults results = _alpr->recognize(matImage.data, matImage.elemSize(), matImage.cols, matImage.rows, regionsOfInterest);
```
