### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [openalpr/openalpr#251]
[Extra null pointer checks are not needed](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8 "Do I need to check for NULL before delete p?") in [the destructor for the class "AlprImpl"](https://github.com/openalpr/openalpr/blob/1a64daf8a61793c20d9362a50eaaec2de08d682c/src/openalpr/alpr_impl.cpp#L77 "Destructor for AlprImpl").

**Comment by matthill** [comment]
Cool, I was not aware of that.  Yes, it makes sense to remove them since they seem to be unnecessary.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/openalpr/openalpr/commit/65ffa5d5606805f318e8999edb67ad336b6f641d "Deletion of a few unnecessary checks").
