### ISSUE TITLE
Improve edge detection on high-contrast LPR cameras

### ISSUE THREAD

**Issue by ssmelov** [openalpr/openalpr#260]
I have the image where a single character is not recognized on the license plate.
Could you give me a hint what parameters should be adjusted in the openalpr.conf file in order to get this character recognized correctly?

Original image:
![good1](https://cloud.githubusercontent.com/assets/1098037/12298333/9be9fdb8-ba22-11e5-8973-7529ae8dd2e8.jpg)

OpenALPR output:
![main](https://cloud.githubusercontent.com/assets/1098037/12298512/7fbfe25a-ba23-11e5-9861-69e40b59bd02.png)

Character segmenter thresholds:
![character-segmenter-thresholds](https://cloud.githubusercontent.com/assets/1098037/12298529/92fd7a8a-ba23-11e5-8878-834dd6d6c10a.png)

**Comment by matthill** [comment]
Thanks for posting this.  I ran it through and noticed that it did find the 4, just with lower accuracy.

mhill@mattlaptop-Satellite-P75-A:/tmp$ alpr ./9be9fdb8-ba22-11e5-8973-7529ae8dd2e8.jpg  -p il
Config file location provided via default location
Analyzing: us
Plate inverted: 0
plate0: 10 results
    - R43725	 confidence: 83.6495	 pattern_match: 1
    - R3725	 confidence: 80.9531	 pattern_match: 0
    - R4372S	 confidence: 79.7767	 pattern_match: 0
    - R372S	 confidence: 77.0802	 pattern_match: 0
    - R437254	 confidence: 75.0113	 pattern_match: 1
    - R43T25	 confidence: 74.1936	 pattern_match: 0
    - R437256	 confidence: 73.6258	 pattern_match: 1
    - R43725G	 confidence: 73.5915	 pattern_match: 0
    - R4325	 confidence: 73.1387	 pattern_match: 0
    - R43725E	 confidence: 72.9512	 pattern_match: 0

There are 2 reasons why it scored it lower:

1. We don't train OCR for every state, just a subset.  I'm assuming this is IL... so adding IL training would probably help.  Although, if you compare the "4" character to other states that we do have training for, it looks *very* similar to AZ and CA, so it may not help that much.
2. The bigger issue is the slope of the line chosen for the bottom edge.  The edge detection did a poor job picking out the edge, especially given the ludicrously high contrast.  I've been meaning to add a special feature for folks, like yourselves, who do a great job getting their cameras setup, and provide a very clear picture like this.  There are two things we can do to make this better:

  - Use an alternative edge detector other than Hough lines.  Hough lines work great when it's a normal daylight picture.  The edges are much harder to pick out in that case.  In your picture, you have crystal clear black-on-white to form the edge of the plate.  We should have a simpler edge detector that just clips the edges based on that high-contrast.
  - Resolve issue #147.  This would give the OCR engine the full "4" character, and wouldn't clip it along the bottom.  The confidence would then be high enough to make it a top choice.

**Comment by matthill** [comment]
Similar european plate example that could use better edge detection
![015](https://cloud.githubusercontent.com/assets/508260/12325662/b9d29322-ba99-11e5-87d4-54b96a231139.jpg)

**Comment by ssmelov** [comment]
Hello Matt,
Thank you very much indeed for the detailed explanation of the issue.
I will try to apply the proposed fixes and will get back to you as soon as I have the result.

**Comment by matthill** [comment]
Implemented an automatic high-contrast detector and morphology/contour-based plate edge finder in edgefinder.cpp (commit 8972e6373dfb34d65eea6e01a8b7742dc0391bc5)

It does a better job at picking up these types of plates, and does not seem to cause a reduction of accuracy for low-contrast plates.

plate0: 10 results
    - R43725	 confidence: 83.805
    - R437254	 confidence: 77.764
    - R437256	 confidence: 76.718
    - R4372S	 confidence: 76.0731
    - R43725G	 confidence: 76.02
    - R3725	 confidence: 74.6598
    - R4325	 confidence: 74.428
    - R43T25	 confidence: 74.3344
    - R437Z5	 confidence: 73.1194
    - R4372	 confidence: 71.4352

plate0: 10 results
    - 1KFH467	 confidence: 90.6265
    - 1KFH4G7	 confidence: 83.4639
    - 1KFH4B7	 confidence: 82.6895
    - 1KFH4S7	 confidence: 82.4093
    - 1KFH47	 confidence: 78.578
    - 1KFM467	 confidence: 77.0096
    - 1KFM4G7	 confidence: 69.847
    - 1KFM4B7	 confidence: 69.0727
    - 1KFM4S7	 confidence: 68.7924
    - 1KFM47	 confidence: 64.9612
