### ISSUE TITLE
How i can add function detect Plate box on C#?

### ISSUE THREAD

**Issue by seekerquoc** [openalpr/openalpr#264]
Hello

How i can add function detect plate box on c# like function recognize?

Thanks

**Comment by matthill** [comment]
I'm not sure what you're asking.  What would function detect plate box do?  You're looking to use the C# binding for this?

**Comment by seekerquoc** [comment]
yes, I need a funtion detect plate box on C# openalpr-net

thanks

**Comment by matthill** [comment]
I'm sorry I don't understand what you're asking for.

**Comment by strdex** [comment]
seekerquoc ?  

Can you need this . Picture Box in motion dedect to Plate in C# with function?  


I am writing to do  with Vb.net
