### ISSUE TITLE
Save recognized plate

### ISSUE THREAD

**Issue by Samani** [openalpr/openalpr#272]
Hi matthill

is  it possible to show me a way to save position of plate recognized in an image like images in README.md file ?

thanks.

**Comment by matthill** [comment]
The position is included in the results that come out of the library.  x1,y1 -> x4,y4 correspond to the four corners of the license plate in clockwise order.  The simplest way to see this data is to run the command line (alpr) and use the -j option to show all the JSON data.

**Comment by Samani** [comment]
Thanks matthill
