### ISSUE TITLE
UnsatisfiedLinkError: jni.Alpr.initialize(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;) when compiling in Java

### ISSUE THREAD

**Issue by aubryll** [openalpr/openalpr#276]
I have been trying to make this work for the past 4 days now and no progress, the only progress I have made is migrating from the no openalprjni in java.library.path to this one, according to https://groups.google.com/forum/#!topic/openalpr/VE2daHHUoi4 discussion I have to put all my dlls, config file and runtime_data directly in the same folder, I decided before I could do anything to try and point my library path to the original OpenAlpr directory where everything is in place, and it did not work so I put all the mentioned data in my workspace still nothing, I tried adding the dlls to system 32 it did not work, I then tried adding my OpenAplr folder to my system path and still nothing worked, is there some voodoo I need to do to make it work? am very confused. I am currently usinf Version 2.0.1 precompiled binraries.

**Comment by matthill** [comment]
Try reviewing the dll with Dependency Walker: http://www.dependencywalker.com/  

That should give you some visibility into which DLLs are not on the path.

**Comment by aubryll** [comment]
on it, I hope this works.

**Comment by aubryll** [comment]
I ran Walker against openalprjni.dll and the output was it could not find IESHIMS.DLL which seem to contain SHLWAPI.DLL and IEFRAME.DLL

**Comment by matthill** [comment]
What does your folder structure look like?  How are you running the Java program?  There is a test Java program included with the release zip, are you able to run that on the command line?  Which DLLs are in/near your java program?

**Comment by aubryll** [comment]
I copied the test program to my workspace and created a new project, then I added the dlls to the root of my project and added it to build path here are Images showing how I set it up [https://drive.google.com/drive/u/0/folders/0ByjesmIMjqfzVWVaLVVtQnVPVFE](url)

**Comment by matthill** [comment]
I think that's a private Google Drive folder, I can't see inside of it.

**Comment by aubryll** [comment]
Am sorry, Here are the images.


![1](https://cloud.githubusercontent.com/assets/13038643/12868506/ed29b194-cca3-11e5-9735-89b24cc0c8fa.PNG)
![Uploading 6.PNG…]()

![2](https://cloud.githubusercontent.com/assets/13038643/12868507/ed3b2c62-cca3-11e5-9cc8-36ba2c4ed5f1.PNG)
![3](https://cloud.githubusercontent.com/assets/13038643/12868508/ed43da56-cca3-11e5-9388-feae4b854b66.PNG)
![4](https://cloud.githubusercontent.com/assets/13038643/12868509/ed47f01e-cca3-11e5-82f4-fa8222561a14.PNG)
![5](https://cloud.githubusercontent.com/assets/13038643/12868510/ed6cc380-cca3-11e5-88f2-f377745a5860.PNG)

**Comment by aubryll** [comment]
![4](https://cloud.githubusercontent.com/assets/13038643/12868564/dfea321e-cca4-11e5-844f-d80d16136633.PNG)
![6](https://cloud.githubusercontent.com/assets/13038643/12868565/dfef1b3a-cca4-11e5-8376-0455087d2dc0.PNG)

**Comment by matthill** [comment]
Your DLLs are all in the same directory, so they see each other.  But your Java program does not know where to look.  Try setting Java's library path to the location of your DLLs: 

http://stackoverflow.com/questions/1734207/how-to-set-java-library-path-for-processing

**Comment by aubryll** [comment]
Thank you let me let me try that.

**Comment by aubryll** [comment]
it did not help, is there another way I could integrate your library with my java code.

**Comment by matthill** [comment]
You may find it helpful learning a bit about JNI, if you're not already familiar with it:
https://en.wikipedia.org/wiki/Java_Native_Interface
https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html

It is the best supported way of calling native code through Java.  That's how we do it with OpenALPR.

**Comment by aubryll** [comment]
Error has been resolved, I think you should add this to your documentation for users like me who have/had absolutely no idea on how this works, so the answer is basically this [answer](http://stackoverflow.com/a/35280078/5896553) , the bad side of using pre-compiled binaries is one has to maintain the folder structure/project structure, so I was having that issue because openAlpr is compiled against >com_openalpr_jni_Alpr and not >mypackagename, Aplr constructor should always match its native counterpart in >com_openalpr_jni_Alpr.h  > JNIEXPORT void JNICALL Java_com_openalpr_jni_Alpr_initialize(JNIEnv *, jobject, jstring, jstring, jstring) minus that it will not never work

**Comment by matthill** [comment]
Ahh, yes, that makes sense.  You pulled in the integration code to a new package, right?  

I wonder if we added an ant or maven target to package it as a jar if that would make it easier/better to integrate...

**Comment by aubryll** [comment]
yes, I agree with you, a jar/maven would be nice, otherwise this is an awesome library, you have saved me a great deal of work, thanks a lot, but I could do with instructions on how to train it with my own font and dual line plate.

**Comment by matthill** [comment]
You're welcome.  I'll add that as an issue.

Here's instructions for training, in case it helps: http://doc.openalpr.com/accuracy_improvements.html#training-ocr

**Comment by aubryll** [comment]
have a great day.

**Comment by hemilcp** [comment]
Do you think you have added a maven target ? It would make it easier to integrate the code.
Thanks

**Comment by cclcalder** [comment]
Hi there, did you ever add a  jar/maven - it would be very helpful!
