### ISSUE TITLE
patterns are not respected

### ISSUE THREAD

**Issue by fgaudenzi** [openalpr/openalpr#288]
Hello,
i'm playing with the library and i'm having strange behaviour.
my patter (sg.pattern) is:

sg	[A-Z][A-Z][A-Z]####[A-Z]

i don't get why during PostProcess part the results are not only restricted to what is expressed in sg.pattern

I got from debug:
OCR Time: 17.183ms.
PostProcess Line 0 Letter: 0 S -- score: 143.812 -- occurences: 6
PostProcess Line 0 Letter: 0 5 -- score: 40.1671 -- occurences: 2
PostProcess Line 0 Letter: 0 6 -- score: 18.5528 -- occurences: 1
PostProcess Line 0 Letter: 1 J -- score: 98.1278 -- occurences: 4
PostProcess Line 0 Letter: 2 ~ -- score: 172.914 -- occurences: 19
PostProcess Line 0 Letter: 2 H -- score: 58.6335 -- occurences: 6
PostProcess Line 0 Letter: 2 M -- score: 23.6647 -- occurences: 3
PostProcess Line 0 Letter: 2 N -- score: 13.7963 -- occurences: 3
PostProcess Line 0 Letter: 2 U -- score: 10.1558 -- occurences: 3
PostProcess Line 0 Letter: 2 W -- score: 3.42227 -- occurences: 2
PostProcess Line 0 Letter: 2 D -- score: 1.93697 -- occurences: 1
PostProcess Line 0 Letter: 2 0 -- score: 0.476425 -- occurences: 1
PostProcess Line 0 Letter: 3 7 -- score: 120.656 -- occurences: 6
PostProcess Line 0 Letter: 3 ~ -- score: 1.93411 -- occurences: 2
PostProcess Line 0 Letter: 4 Q -- score: 124.876 -- occurences: 5
PostProcess Line 0 Letter: 4 0 -- score: 105.072 -- occurences: 4
PostProcess Line 0 Letter: 4 D -- score: 72.823 -- occurences: 3
PostProcess Line 0 Letter: 4 G -- score: 49.8071 -- occurences: 3
PostProcess Line 0 Letter: 4 B -- score: 16.5617 -- occurences: 1
PostProcess Line 0 Letter: 5 5 -- score: 148.288 -- occurences: 6
PostProcess Line 0 Letter: 5 S -- score: 55.3132 -- occurences: 3
PostProcess Line 0 Letter: 5 B -- score: 32.6039 -- occurences: 3
PostProcess Line 0 Letter: 5 ~ -- score: 12.3961 -- occurences: 3
PostProcess Line 0 Letter: 6 Q -- score: 163.492 -- occurences: 6
PostProcess Line 0 Letter: 6 0 -- score: 76.1787 -- occurences: 3
PostProcess Line 0 Letter: 6 G -- score: 49.6778 -- occurences: 3
PostProcess Line 0 Letter: 6 D -- score: 45.6367 -- occurences: 2
PostProcess Line 0 Letter: 6 ~ -- score: 0.380829 -- occurences: 1
PostProcess Line 0 Letter: 7 Y -- score: 131.83 -- occurences: 6
 -- PostProcess Permutation Time: 0.09ms.
Top 10 Possibilities: SJ7Q5QY :	87.0776 <--- 
Top 10 Possibilities: SJ705QY :	85.5156
Top 10 Possibilities: SJ7D5QY :	82.9719
Top 10 Possibilities: SJ7G5QY :	81.1566
Top 10 Possibilities: SJ7Q50Y :	80.1908
Top 10 Possibilities: SJ7QSQY :	79.7442
Top 10 Possibilities: 5J7Q5QY :	78.9026
Top 10 Possibilities: SJ7050Y :	78.6287
Top 10 Possibilities: SJ7B5QY :	78.5343
Top 10 Possibilities: SJ70SQY :	78.1822
10 total permutations
PostProcess Time: 0.358ms.
PostProcess Analysis Complete: SJ7Q5QY -- MATCH: 0

Indeed S is right, J is right, 7 doesn't respect the pattern, Q doesn't respect the pattern, 5 is right, Q doesn't respect the pattern, Y is right.

How can i check that the pattern is correctly enforced?

Thanks.

**Comment by matthill** [comment]
When it matches a pattern, it will flag it with the pattern match variable set to 1:
http://doc.openalpr.com/accuracy_improvements.html#pattern-matching

If you want to ignore anything that doesn't match the pattern, you can enable this option:
https://github.com/openalpr/openalpr/blob/master/config/openalpr.conf.in#L47
