### ISSUE TITLE
I'm confused about the angle judge rule of line 214 codes in characteranalysis.cpp 

### ISSUE THREAD

**Issue by SunAriesCN** [openalpr/openalpr#291]
“     // Use the angle for the first line -- assume they'll always be parallel for multi-line plates
      int absangle = abs(pipeline_data->textLines[0].topLine.angle);
      if (absangle > config->maxPlateAngleDegrees)
        confidenceDrainers += 91;
      else if (absangle > 1)
        confidenceDrainers += (config->maxPlateAngleDegrees - absangle) ;    ”

Above is your code arround there. I don't understand why confidenceDrainers get 0 score when absangle = config->maxPlateAngleDegrees? I think it should get higher score here, doesn't it?

**Comment by matthill** [comment]
Yes, you're right.  That looks like a bug.  The intention was (as you correctly guessed) to penalize plates with higher angles.
