### ISSUE TITLE
Indonesian License Plates

### ISSUE THREAD

**Issue by simplyeazy** [openalpr/openalpr#293]
Hello Matt

So I tried to train the OCR in train-ocr repository and the train.py didn't work. I've tried adjusting the tesseract dir path to my tesseract installation directory in ubuntu but still it says missing something like:
Two-Letter Country Code to Train: id
Processing: ./id/input/lid.indonesiaplatefont.exp0.box
Executing: /home/simplyeazy/Downloads/tesseract/tesseract -l eng ./id/input/lid.indonesiaplatefont.exp0.tif lid.indonesiaplatefont.exp0 nobatch box.train.stderr
sh: 1: /home/simplyeazy/Downloads/tesseract/tesseract: not found
mv: cannot stat ‘./lid.indonesiaplatefont.exp0.tr’: No such file or directory
mv: cannot stat ‘./lid.indonesiaplatefont.exp0.txt’: No such file or directory
sh: 1: /home/simplyeazy/Downloads/tesseract/training/unicharset_extractor: not found
Executing: /home/simplyeazy/Downloads/tesseract/training/mftraining -F ./tmp/font_properties -U unicharset -O ./tmp/lid.unicharset ./tmp/*.tr
I'm pretty new to Linux and tesseract and tried for like 2 weeks and still can't figure out what is wrong with my ocr training process.

Attached below is the TTF of Indonesia License Plate (the O and 0 are switched in the TTF so please use O when writing 0) please help me to get the traineddata. Thank you. 

[IndoLicensePlate.zip](https://github.com/openalpr/openalpr/files/156929/IndoLicensePlate.zip)

![indonesian fonts](https://cloud.githubusercontent.com/assets/6694017/13497116/4ffd863c-e186-11e5-955b-c700fab67951.JPG)

**Comment by matthill** [comment]
You'll need to get binaries (or compile) Tesseract for your system: https://github.com/tesseract-ocr/tesseract

The Tesseract training tools are used to train the ocr data

**Comment by andikaj** [comment]
Hello simplyeazy,

Please test our explore about trained data indonesian license plate.
File result attached.


![b1963bjp](https://cloud.githubusercontent.com/assets/29059499/26578097/c0c82aac-4558-11e7-85b8-3a7ef8ebc1c1.jpg)
[hasiltuningb1963bjp.txt](https://github.com/openalpr/openalpr/files/1037888/hasiltuningb1963bjp.txt)
[id.conf.txt](https://github.com/openalpr/openalpr/files/1037889/id.conf.txt)
[id.patterns.txt](https://github.com/openalpr/openalpr/files/1037894/id.patterns.txt)
[id.xml.txt](https://github.com/openalpr/openalpr/files/1037895/id.xml.txt)
[lid.traineddata.txt](https://github.com/openalpr/openalpr/files/1037897/lid.traineddata.txt)
[openalpr.conf.txt](https://github.com/openalpr/openalpr/files/1037899/openalpr.conf.txt)

please remove for txt extention except "hasiltuningb1963bjp.txt"

**Comment by andikaj** [comment]
Hi Matt,
I have already put number 1 on each debug option within /etc/openalpr.conf. But, when i run command [alpr -c id /source/images.jpg --debug]. The recognition result on images only view temporary.
How to show recognition result on images ?

**Comment by simplyeazy** [comment]
@andikaj Thank you for helping me out. Sorry, I forgot to close the issue. It's not an issue with openalpr but I and I've since solved the problem. For your question, please open a new issue for it.

**Comment by reza4836** [comment]
Hello @andikaj , thank you for the training results file. By the way, how did you execute the training file (.box and .tif) to be generated as .traineddata file? I'd completely stuck by this error command. I want to train another .tif and .box file.

Two-Letter Country Code to Train: id
Processing: ./id/input/lid.indonesia.exp0.box
Executing: /media/gspeintercon/GSPE1/GIT/tesseract-4.0.0-beta.1/tessdata -l eng ./id/input/lid.indonesia.exp0.tif lid.indonesia.exp0 nobatch box.train.stderr
sh: 1: /media/gspeintercon/GSPE1/GIT/tesseract-4.0.0-beta.1/tessdata: Permission denied
mv: cannot stat './lid.indonesia.exp0.tr': No such file or directory
mv: cannot stat './lid.indonesia.exp0.txt': No such file or directory
Extracting unicharset from box file ./id/input/lid.indonesia.exp0.box
Other case a of A is not in unicharset
Other case b of B is not in unicharset
Other case c of C is not in unicharset
Other case d of D is not in unicharset
Other case e of E is not in unicharset
Other case f of F is not in unicharset
Other case g of G is not in unicharset
Other case h of H is not in unicharset
Other case i of I is not in unicharset
Other case j of J is not in unicharset
Other case k of K is not in unicharset
Other case l of L is not in unicharset
Other case m of M is not in unicharset
Other case n of N is not in unicharset
Other case o of O is not in unicharset
Other case p of P is not in unicharset
Other case q of Q is not in unicharset
Other case r of R is not in unicharset
Other case s of S is not in unicharset
Other case t of T is not in unicharset
Other case u of U is not in unicharset
Other case v of V is not in unicharset
Other case w of W is not in unicharset
Other case x of X is not in unicharset
Other case y of Y is not in unicharset
Other case z of Z is not in unicharset
Wrote unicharset file unicharset
Executing: /media/gspeintercon/GSPE1/GIT/tesseract-4.0.0-beta.1/training/mftraining -F ./tmp/font_properties -U unicharset -O ./tmp/lid.unicharset ./tmp/*.tr
Warning: No shape table file present: shapetable
Reading ./tmp/*.tr ...

Error: Unable to open ./tmp/*.tr!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75
Segmentation fault (core dumped)
mv: cannot stat './tmp/lid.unicharset': No such file or directory
cp: cannot stat './id/input/unicharambigs': No such file or directory
Reading ./tmp/*.tr ...

Error: Unable to open ./tmp/*.tr!
"Fatal error encountered!" == NULL:Error:Assert failed:in file globaloc.cpp, line 75
Segmentation fault (core dumped)
mv: cannot stat './shapetable': No such file or directory
mv: cannot stat './pffmtable': No such file or directory
mv: cannot stat './inttemp': No such file or directory
mv: cannot stat './normproto': No such file or directory
Combining tessdata files
Error: traineddata file must contain at least (a unicharset fileand inttemp) OR an lstm file.
Error combining tessdata files into lid.traineddata
Version string:4.00.00alpha
23:version:size=12, offset=192
mv: cannot stat './lid.unicharset': No such file or directory
mv: cannot stat './lid.shapetable': No such file or directory
mv: cannot stat './lid.pffmtable': No such file or directory
mv: cannot stat './lid.inttemp': No such file or directory
mv: cannot stat './lid.normproto': No such file or directory
mv: cannot stat './lid.unicharambigs': No such file or directory

Thanks before.

**Comment by Agus1995** [comment]
@andikaj  sorry, what version tesseract are you using? i have an error "actual_tessdata_num_entries_ <= TESSDATA_NUM_ENTRIES:Error:Assert failed:in file tessdatamanager.cpp, line 53 Segmentation fault"

**Comment by luthfitabey** [comment]
Guys please help me, how to make folder config, keypoints, ocr, postprocess with tesseract [https://drive.google.com/open?id=10cOh5jLreVyrrQH2_F_PUb8_PktH1ekq]

**Comment by MarCovy** [comment]
@luthfitabey what kind of problem do you have ? Can you describe more your problem ?

**Comment by luthfitabey** [comment]
how can i make those folder in windows. i heve'nt understand yet about
that. can u give me tutorial about alpr making

​

**Comment by alucard079** [comment]
@reza4836 You can use your tif and box file with other tools to produce `traineddata`
