### ISSUE TITLE
Valid tasks param values

### ISSUE THREAD

**Issue by ClayApps** [openalpr/openalpr#295]
I have signed up, grabbed the YUML, loaded into Swagger and generated Swift code. The API is asking for  tasks param (String). I have hunted around but am unable find what I need here?

```swift
public class func recognizePostWithRequestBuilder(secretKey secretKey: String, tasks: [String], image: NSURL, imageBytes: String?, imageUrl: String?, country: String?, state: String?, returnImage: Int?, topn: Int?, prewarp: String?) -> RequestBuilder<Inline_response_200> {
        let path = "/recognize"
        let URLString = SwaggerClientAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "secretKey": secretKey,
            "tasks": tasks,
            "imageBytes": imageBytes,
            "imageUrl": imageUrl,
            "country": country,
            "state": state,
            "returnImage": returnImage,
            "topn": topn,
            "prewarp": prewarp
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Inline_response_200>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: parameters, isBody: false)
    }
```

**Comment by matthill** [comment]
The task is what operation you wish to perform (i.e., plate recognition, vehicle make, make-model, or color).  If you want to do multiple tasks in one pass, use a comma to separate them.  For example:
plate,color,make,makemodel

**Comment by ClayApps** [comment]
Cool thanks, just need the values!

**Comment by matthill** [comment]
No problem.  I'll update the swagger spec doc to include them.

**Comment by ClayApps** [comment]
I tried a string array per the interface generated by swagger and got:

JSON Recevied [Optional("{\n    error = \"Missing tasks\";\n    \"error_code\" = 400;\n}")]

So I then tried an array of strings with just one per your example attached:

        DefaultAPI.recognizePost(
            secretKey: secretKey,
            tasks: ["plate,color,make,makemodel"],
            image: imageUrl!,
            imageBytes: nil,
            imageUrl: nil,
            country: "us",
            state: "il",
            returnImage: 0,
            topn: 10,
            prewarp: nil,
            completion: dataResponse
        )

And again got:

JSON Recevied [Optional("{\n    error = \"Missing tasks\";\n    \"error_code\" = 400;\n}")]

I think the YUML isn’t right here and perhaps code being generated by swagger has issues also as I get nothing in the completion handler but if i dig around in the Alamofire response I can dig out the above error.

**Comment by ClayApps** [comment]
Here is my code that calls Swagger:

```swift
    @IBAction func test(sender: AnyObject) {
        
//        let tasks = ["plate", "color", "make", "model"]
        let secretKey = Constants.OpenALR.OpenALRSecretKey
        let imageUrl = NSBundle.mainBundle().URLForResource("CarAndPlate1", withExtension: "jpeg")
        
        DefaultAPI.recognizePost(
            secretKey: secretKey,
            tasks: ["plate,color,make,makemodel"],
            image: imageUrl!,
            imageBytes: nil,
            imageUrl: nil,
            country: "us",
            state: "il",
            returnImage: 0,
            topn: 10,
            prewarp: nil,
            completion: dataResponse
        )
        
    }
    
    func dataResponse(data: Inline_response_200?, error: ErrorType?) -> Void {        
        print("\(error.debugDescription)")
        print("\(data?.creditsMonthlyUsed)")
        print("\(data?.creditsMonthlyTotal)")
        print("\(data?.imgWidth)")
        print("\(data?.color)")
        print("\(data?.makemodel)")
        print("\(data?.totalProcessingTime)")
        print("\(data?.imgHeight)")
        print("\(data?.creditCost)")
        print("\(data?.plate?.results?.first?.plate)")
        print("\(data?.make)")
    }
```

**Comment by ClayApps** [comment]
Here's some response using just ["make"] as a task:

```swift
Request : XMethod : Optional(Alamofire.Method.POST)
Request : Params  : ["tasks": (
    make
), "topn": 10, "secretKey": sk_6820e1061b7559544e13d369, "country": us, "returnImage": 0, "state": il]
JSON Recevied [Optional("{\n    error = \"Missing tasks\";\n    \"error_code\" = 400;\n}")]
``

**Comment by matthill** [comment]
Can you tell what's being sent in the POST to the Cloud API?  The tasks should simply be a list of values separated by comma (e.g., make,plate).

I wonder if the Swagger generator may work slightly differently for Swift.

**Comment by ClayApps** [comment]
Working on it ...

**Comment by ClayApps** [comment]
Further, I hacked the Swagger API to allow a string rather than an array of string and added "on" for the state :) I also moved to using base64 encoding of the image as the imageUrl thing is confusing in the API and Swagger is forcing the image param so I hacked that to allow me to send base64.

```swift
    @IBAction func test(sender: AnyObject) {
        
//        let tasks = ["plate", "color", "make", "model"]
        // "plate,color,make,makemodel"
        let secretKey = Constants.OpenALR.OpenALRSecretKey
        let imagepath = NSBundle.mainBundle().pathForResource("CarAndPlate1", ofType: "jpeg")  //("CarAndPlate1", : "jpeg")
        let carImage = UIImage(contentsOfFile: imagepath!)
        let carImageData = UIImagePNGRepresentation(carImage!)
        let carImageDataBase64String = carImageData!.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)

        DefaultAPI.recognizePost(
            secretKey: secretKey,
            tasks: "make",
            image: nil,
            imageBytes: carImageDataBase64String,
            imageUrl: nil,
            country: "us",
            state: "on",
            returnImage: 0,
            topn: 10,
            prewarp: nil,
            completion: dataResponse
        )
        
    }
```

Now I am getting:

SON Recevied [Optional("{\n    error = \"Missing secret_key\";\n    \"error_code\" = 400;\n}")] 

Sweet, getting closer! Here is my latest request / response log:

```swift

Request : XMethod : Optional(Alamofire.Method.POST)
Request : Params  : ["imageBytes": iVBORw0KGgoAAAANSUhEUgAAARQAAAC3CAIAAABc7TbaAAAAAXNSR0IArs4c6QAA

BLAH BLAH BLAH

KqZAIAQwLudhi/LA8/8BBvKTvxbNppUAAAAASUVORK5CYII=, "topn": 10, "secretKey": sk_6820e1061b7559544e13d369, "country": us, "returnImage": 0, "tasks": make, "state": on]
JSON Recevied [Optional("{\n    error = \"Missing secret_key\";\n    \"error_code\" = 400;\n}")]
(lldb) 
```

**Comment by ClayApps** [comment]
Right changed the secret key param name from "secretKey" to "secret_key" now I am getting:

JSON Recevied [Optional("{\n    error = \"no image specified\";\n    \"error_code\" = 400;\n}")]

therefore let me try "image_bytes" got yhr param name

**Comment by ClayApps** [comment]
BOOM!

JSON Recevied [Optional("{\n    \"credit_cost\" = 1;\n    \"credits_monthly_total\" = 1500;\n    \"credits_monthly_used\" = 1;\n    \"img_height\" = 183;\n    \"img_width\" = 276;\n    make =     (\n                {\n            confidence = \"86.2204\";\n            value = toyota;\n        },\n                {\n            confidence = \"6.50928\";\n            value = chevrolet;\n        },\n                {\n            confidence = \"2.42655\";\n            value = honda;\n        },\n                {\n            confidence = \"1.3417\";\n            value = porsche;\n        },\n                {\n            confidence = \"1.09549\";\n            value = mitsubishi;\n        }\n    );\n    \"total_processing_time\" = \"485.9730000000582\";\n}")]

Phew!

**Comment by ClayApps** [comment]
You'll have a bunch of bugs in the YAML at least! Many thanks for your help today!!!

**Comment by ClayApps** [comment]
Also: 

```swift
   func dataResponse(data: Inline_response_200?, error: ErrorType?) -> Void {        
        print("\(error.debugDescription)")
        print("\(data?.creditsMonthlyUsed)")
        print("\(data?.creditsMonthlyTotal)")
        print("\(data?.imgWidth)")
        print("\(data?.color)")
        print("\(data?.makemodel)")
        print("\(data?.totalProcessingTime)")
        print("\(data?.imgHeight)")
        print("\(data?.creditCost)")
        print("\(data?.plate?.results?.first?.plate)")
        print("\(data?.make)")
    }

```
Returns nil for everything, so problems in the Swagger code, but thats for tomorrow.
