### ISSUE TITLE
Low light situations aka night

### ISSUE THREAD

**Issue by ClayApps** [openalpr/openalpr#297]
I looked around your docs after testing a nice night pic and was wondering what your nighttime strategy is?

**Comment by matthill** [comment]
Can you upload a sample picture?  Infrared images generally work well.

**Comment by ClayApps** [comment]
Here you go:

**Comment by matthill** [comment]
Hey Clay, I don't think the file made it through.  I don't see anything attached.

**Comment by ClayApps** [comment]
Try this :

**Comment by matthill** [comment]
Hmm, still looks empty

**Comment by ClayApps** [comment]
trying again
![img_3219](https://cloud.githubusercontent.com/assets/1844356/13726346/4762ea64-e878-11e5-847f-90a7da56e093.JPG)
![img_3218](https://cloud.githubusercontent.com/assets/1844356/13726350/6e97d9c8-e878-11e5-9d9f-795c06c5a323.JPG)

**Comment by matthill** [comment]
That seems to be a perspective issue.  The shots are close-up at an angle, and the image is stretched horizontally as well.  You can fix this with the calibrate utility:
http://doc.openalpr.com/accuracy_improvements.html#calibration

When I run the calibration utility, I get these settings:
prewarp = planar,1024.000000,1024.000000,0.000550,0.000000,-0.020000,1.235000,1.005000,0.000000,0.000000

Applying that to openalpr.conf, makes both images come out correct.

plate0: 10 results
    - 6Z0K233	 confidence: 93.8845
    - 6ZOK233	 confidence: 87.2567
    - 6ZQK233	 confidence: 86.6172
    - 6ZDK233	 confidence: 86.0597
    - 620K233	 confidence: 85.351
    - 6ZUK233	 confidence: 84.6179
    - 6Z0KZ33	 confidence: 84.6067
    - 6ZGK233	 confidence: 84.1345
    - 6ZBK233	 confidence: 81.5357
    - 6ZK233	 confidence: 80.2578


plate0: 10 results
    - 6Z0K233	 confidence: 92.6111
    - 6ZOK233	 confidence: 85.5589
    - 620K233	 confidence: 85.1347
    - 6ZDK233	 confidence: 84.9944
    - 6ZQK233	 confidence: 84.897
    - 6Z0KZ33	 confidence: 83.0435
    - 6ZUK233	 confidence: 83.0135
    - 6ZBK233	 confidence: 82.9661
    - 6ZGK233	 confidence: 79.5921
    - 62OK233	 confidence: 78.0825
