### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by DuyguA** [openalpr/openalpr#302]
Hello,

Video processing is a bit slow for my purposes. 
Is there a multithreaded  implementation available? Or anybody modified main.cpp for multithreading?

Thanx in advance.

**Comment by matthill** [comment]
The commercial implementation has a video processing feature that is multi-threaded:
http://doc.openalpr.com/video_processing.html

The open source library is single-threaded, but it would not be hard to add code to multi-thread the library.  Just make sure you run a separate OpenALPR instance on each thread.
