### ISSUE TITLE
openalpr-utils-binarizefontsheet no result file

### ISSUE THREAD

**Issue by agustoklik** [openalpr/openalpr#308]
i use openalpr-utils-binarizefontsheet to produce tiles, but why no result file in my directory ?
![no-output](https://cloud.githubusercontent.com/assets/11517390/13944444/58609c56-f040-11e5-853d-312ae0fe8d84.JPG)
what im doing wrong ?

**Comment by matthill** [comment]
Confirmed resolved in Google forum
