### ISSUE TITLE
Error while running test.py using python bindings

### ISSUE THREAD

**Issue by kudhru** [openalpr/openalpr#311]
Hi

I have followed all the instructions for installing openalpr on ubuntu.
However, when I try to use the python binding to run the following command:

`python test.py -c us exampleImage.jpg`

I get the following error:
`openalprpy.cpp: In function ‘void setCountry(alpr::Alpr*, char*)’:
openalprpy.cpp:104:19: error: ‘class alpr::Alpr’ has no member named ‘setCountry’
       nativeAlpr->setCountry(country);
                   ^
openalprpy.cpp: In function ‘void setPrewarp(alpr::Alpr*, char*)’:
openalprpy.cpp:112:19: error: ‘class alpr::Alpr’ has no member named ‘setPrewarp’
       nativeAlpr->setPrewarp(prewarp);
                   ^
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    alpr = Alpr(options.country, options.config, options.runtime_data)
  File "/home/ashu/Desktop/ALPR GIT HUB/openalpr-master/src/bindings/python/openalpr/openalpr.py", line 81, in __init__
    self._set_country_func = self._openalprpy_lib.setCountry
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libopenalprpy.so: undefined symbol: setCountry
Exception AttributeError: "Alpr instance has no attribute 'alpr_pointer'" in <bound method Alpr.__del__ of <openalpr.openalpr.Alpr instance at 0x7f08f35f2d88>> ignored
`
 
Also, note that running the following command works fine:
`alpr -c us exampleImage.jpg`

So, it seems like the package works fine but there is some problem in the python binding.

Can someone please help me out here please? I have been dying to use this library for a while now.

Thanks
Dhruv

**Comment by matthill** [comment]
It looks like you're using the newer Python bindings with an older OpenALPR library, is that right?  If you checked out and built version 2.2 from git, you should use the Python bindings on that tag.

The newer Python bindings reference functions that don't exist in v2.2 (they only exist in the newer code).  Those functions are named setPrewarp, setCountry, etc.

**Comment by tirth456** [comment]
It seems like that you are using Indian number plate. This openalpr works only on us and some other country. They didn't train for India. So you have to train by yourself to get this result. Else you can use us no plate it works fine.

**Comment by JecintaMulongo** [comment]
@matthill 
I encountered this error while running openalpr in pycharm:
AttributeError: /usr/lib/libopenalpr.so.2: undefined symbol: openalpr_add_encoded_image_to_batch
Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x7f1ef1434d68>>
Traceback (most recent call last):
  File "/virtualenvs/cv/lib/python3.6/site-packages/openalpr/openalpr.py", line 159, in __del__
    if self.is_loaded():
  File "/.virtualenvs/cv/lib/python3.6/site-packages/openalpr/openalpr.py", line 212, in is_loaded
    if not self.loaded:
AttributeError: 'Alpr' object has no attribute 'loaded'

any solution
