### ISSUE TITLE
How to debug the program output the results for each step

### ISSUE THREAD

**Issue by zh453** [openalpr/openalpr#313]
Recently, I study this project, I want to see for each step output, unfortunately, I cannot debug the results for each step, I do not know whether you are willing to help me, thank you

**Comment by matthill** [comment]
Try with the --debug option on the command line, that should output various graphics and text data to the console.  You can follow along in the code for what particular area you wish to modify/improve.

**Comment by zh453** [comment]
Thank you for your answer,I will try it .
