### ISSUE TITLE
Recognizing Alberta (Canada) License Plates

### ISSUE THREAD

**Issue by andrewaggb** [openalpr/openalpr#314]
Hi,

Alberta (Canada) license plates have red text on a white background.  I did some brief testing with a few images using the US settings and alpr.exe and no plates could be found.  After going into paint.net and making the letters black instead of red things are detected fine.

Where should I start in the code or configs to get this working?  I'm assuming this is a contrast ratio issue.

**Comment by matthill** [comment]
Alberta plates are recognized well, as far as I know.  They're similar to Massachusetts plate (red letters on a white background).  Perhaps if you can post the original images that you tried, there may be another reason that they're not recognizing.

![alberta](https://cloud.githubusercontent.com/assets/508260/14215132/0b5a7784-f80f-11e5-8e48-548ca9e00414.png)

**Comment by andrewaggb** [comment]
Actually you are correct...  I just tried it again using alpr.exe v 2.20 and that image and a couple others  worked for me with stock settings.  I must have run it with different settings.  I apologize.
