### ISSUE TITLE
Can we find a paper which report about OpenALPR?

### ISSUE THREAD

**Issue by astrung** [openalpr/openalpr#315]
Now,i try to modify the recognition code of OpenALPR,but it is hard because document for modifying the recognition code is out-of-date : [here](http://doc.openalpr.com/accuracy_improvements.html#developers-guide).So can we find a paper report Open ALPR ( to understand this code)

**Comment by matthill** [comment]
Best way is to dig in and ask questions on the forum once you get stuck with something or need clarification.  If there's particular things that are out of date, please let me know.  Or you could update the documentation directly: https://github.com/openalpr/openalpr/tree/master/doc/source
