### ISSUE TITLE
How to config for  plate background red - EU Remolque

### ISSUE THREAD

**Issue by newsages** [openalpr/openalpr#318]
http://www.matriculaseuropeas.com/images/product9m_20160208112504.jpg
plate double line: 340x220
plate single line: 620x110
chars: 77x45x10 mm 
background Red.

thx

**Comment by matthill** [comment]
The single line plates probably work as-is, but could be improved with training.  The two-line plates require training.  Documentation is available here:
http://doc.openalpr.com/accuracy_improvements.html#training-ocr
