### ISSUE TITLE
What should i exactly do for training Indian number plates? 

### ISSUE THREAD

**Issue by muralidharan-murugan** [openalpr/openalpr#323]
Please help me.. What should i exactly do for training Indian number plates?

I got in.xml file from https://groups.google.com/forum/#!searchin/openalpr/trained/openalpr/M5ehTr8yG-0/0hB0EHgT0AEJ
 
After that what should i exactly do? 
Should i generate traineddata file, pattern file and conf file?

**Comment by matthill** [comment]
There is some documentation about training here:
http://doc.openalpr.com/accuracy_improvements.html#training-the-detector
http://doc.openalpr.com/accuracy_improvements.html#training-ocr

**Comment by sthiruppathi** [comment]
Hello Both,

Could you please share the Indian trained file(in.xml) and configuration file for the same?
