### ISSUE TITLE
Problem passing the /dev/video0

### ISSUE THREAD

**Issue by kamikadzez** [openalpr/openalpr#324]
Problem - using /dev/video0 as input device.
running alpr /dev/video0 or /dev/video1 gives an error message "Unknown file type"
Solution -

    else if (startsWith(filename, "/dev/video")
    {
      int framenum = 0;
      if(filename.length() > 10)
      {
        std::string webcam_str_num;
        for(int a = 11; a <= filename.length(); a=a+1)
        {
          webcam_str_num.append(filename,a,1);
        }
        else
        {
          std::cout << "Incorrect Device Number" << std::endl;
          return 1;
        }
      int webcamnumber = atoi(webcam_str_num.c_str());
      }
      cv::VideoCapture cap(webcamnumber);
      if (!cap.isOpened())
      {
        std::cout << "Error opening webcam" << std::endl;
        return 1;
      }

      while (cap.read(frame))
      {
        if (framenum == 0)
          motiondetector.ResetMotionDetection(&frame);
        detectandshow(&alpr, frame, "", outputJson);
        sleep_ms(10);
        framenum++;
      }
    }

Before i get any blame - this is my first experience with C++ and I am still learning but this was the way to fix this problem.
If you have a better suggestion - please post below.

**Comment by matthill** [comment]
Thanks for posting this.  This looks like a good addition.  I'd be happy to merge a pull request if you want to send one in.

**Comment by kamikadzez** [comment]
Will send one when I get to the office, have another suggestion which includes the custom video resolution as well.

**Comment by kamikadzez** [comment]
Closed and Merged now.
