### ISSUE TITLE
Windows compiler

### ISSUE THREAD

**Issue by zh453** [openalpr/openalpr#325]
I compiled under the Windows, I don't know which step in the wrong, lead to can not run normally, I do not know can you send me a detailed report, and the online video is not clear and there is no sound, can you give me to send ,does not help ,thank you

**Comment by matthill** [comment]
You may want to try posting to the forum https://groups.google.com/forum/#!forum/openalpr

Usually you'll get the best responses by posting specific error messages or issues you're running into.

**Comment by zh453** [comment]
I compile a lot of errors in the win7 about time.h, modify the <sys/timeb.h> for <sys/time.h> there is no use, then what I should do, thank you
