### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib

### ISSUE THREAD

**Issue by alvas** [openalpr/openalpr#326]
I try to run this on OS X El Captain. But there are libraries could not be load.

yld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_highgui.2.4.dylib
  Reason: image not found
Trace/BPT trap: 5

dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_highgui.2.4.dylib
  Reason: image not found
Trace/BPT trap: 5

**Comment by matthill** [comment]
This may help: http://stackoverflow.com/questions/32703296/dyld-library-not-loaded-usr-local-lib-libjpeg-8-dylib-homebrew-php
