### ISSUE TITLE
alprd >1080p

### ISSUE THREAD

**Issue by nayrnet** [openalpr/openalpr#332]
If I set:
```
max_detection_input_width = 1920
max_detection_input_height = 1080
```
any larger than this it seems alprd does not work, I am using the mask to watch a very small strip at high fps, and would like to bump the feed resolution up from 2MP to 4MP as I can can see up to 8 reads per second right now but struggling on some plates due to distance..

is there some sort of limit I am hitting or additional configuration I need?

**Comment by matthill** [comment]
What behavior are you seeing when you try and run with larger values?  Does the program not start?  Does it start but provide different results than what you expect?

**Comment by newsages** [comment]
for me 5312 x 2988 píxeles, work well,
and 2 mods-engines,
![engine2](https://cloud.githubusercontent.com/assets/9095584/14797552/954bea04-0b33-11e6-9b7c-f63a6d9145c1.png)

**Comment by nayrnet** [comment]
it fails to open the stream with any resolution >1080p, as soon as I reconfigure the MJPEG stream to 1080p it connects without issue.

'''
WARN - Stream rtsp://user:pass@192.168.42.19:554/cam/realmonitor?channel=7&subtype=0 failed to open.
INFO - Video stream connecting...
WARN - Stream rtsp://user:pass@192.168.42.19:554/cam/realmonitor?channel=7&subtype=0 failed to open.
INFO - Video stream connecting...
WARN - Stream rtsp://user:pass@192.168.42.19:554/cam/realmonitor?channel=7&subtype=0 failed to open.
INFO - Video stream connecting...
INFO - Video stream connected
'''

**Comment by nayrnet** [comment]
sigh, trying through VLC it seems anything higher than 1080p is messed up.. the reported resolution is not what I have set.. must be an issue with my camera, sorry.
