### ISSUE TITLE
[SOLVED] Valid tasks param values Angularjs

### ISSUE THREAD

**Issue by Digitalab** [openalpr/openalpr#339]
Hy,

I try to use the cloud API in an ionic app.

```
    var secret_key = 'Mysecret';
    var tasks = 'plate';
    var image_url = 'http://www.grisecarte.fr/wp-content/uploads/2013/07/Changement-de-plaque-d%E2%80%99immatriculation-pour-une-carte-grise-300x199.jpg';
    var country = 'eu';
    var state = 'fr';
    var return_image = 0;
    var topn = 1;

    var url = 'https://api.openalpr.com/v1/recognize';
    var parameter = JSON.stringify({secret_key:secret_key, image_url:image_url, tasks:tasks, country:country, state:state, return_image:return_image, topn:topn});
    $http.post(url, parameter).
    success(function(data, status, headers, config) {
        // this callback will be called asynchronously
        // when the response is available
        console.log(data);
      }).
      error(function(data, status, headers, config) {
        // called asynchronously if an error occurs
        // or server returns response with an error status.
      });

```

but i get : {"error_code": 400, "error": "Missing tasks"}

can you help me please?

**Comment by Digitalab** [comment]
In fact i succed. this is working code for intégration in ionic.

`    $scope.getData = function(imageData) {
        var baseUrl = 'https://api.openalpr.com/v1/recognize';
        var secret_key = 'MySecretKey';
        var tasks = 'plate';
        var image_url = 'http://www.grisecarte.fr/wp-content/uploads/2013/07/Changement-de-plaque-d%E2%80%99immatriculation-pour-une-carte-grise-300x199.jpg';
        var image_bytes = imageData; // Without data:image/jpeg;base64,
        var country = 'eu';
        var state = 'fr';
        var return_image = 0;
        var topn = 1;

        $http({
          method: 'POST',
          url: baseUrl,
          data: $httpParamSerializerJQLike({
            "secret_key" : secret_key,
            "tasks" : tasks,
            "image_bytes" : image_bytes,
            "country" : country,
            "state" : state,
            "return_image" : return_image,
            "topn" : topn
          }),
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        }).success(function(data) {
            $scope.plate = data.plate.results[0].plate;
        })
        .error(function(data) {
            alert("ERROR");
        });
    }`

**Comment by matthill** [comment]
Thanks for answering this and updating the issue with your working code!
