### ISSUE TITLE
Add mask region to alpr daemon

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#34]
There are certain areas in the input stream that we don't wish to attempt detection (e.g., sky, a fence area, a timestamp).  Add a black/white mask image as input (resolution must match input stream) that will not attempt detection.

This should be implemented in such a way that it both decreases false positives and improves performance (since less of the image must be analyzed).

**Comment by matthill** [comment]
Implemented in commit a0dff3d2af84b261dd329ff470cd99c2f0e7372c

Providing an image file to openalpr.conf that specifies the valid region (white is valid, black is ignore) the detection process will ignore the dark areas.

**Comment by ad1k4h** [comment]
How can i use as per camera in alprd.conf?
