### ISSUE TITLE
Precompiled libraries samples not working

### ISSUE THREAD

**Issue by Dunge** [openalpr/openalpr#355]
I got the openalpr-2.2.0-win-64bit.zip package and I try to run the sample in the readme.txt file:

alpr -c us samples/us-1.jpg
No license plates found.

Is there anything to configure for this to work?

I also tried the 32bits version, same result. I also compiled the openalprnet-windemo.exe from the source and copied the binary in the precompiled binary folder for it to find the .dll, and loading an image don't get any result.

**Comment by nunonup** [comment]
Get shure you're in the path of the openalpr folder in the cmd...

**Comment by Dunge** [comment]
I am, and running console as administrator. In my case, it is under
C:\Users\Dunge\Desktop\openalpr-2.2.0-win-32bit\openalpr_32bit

If I change the .jpg path, I get a different message so it does launch the application and load the image.

**Comment by nunonup** [comment]
Try other image

**Comment by Dunge** [comment]
No, I made many test it never find anything. Even the video, I see it parsing every frames but don't get any result.

Does this build work for you? Should I try an older version?

The only thing I think that may influence is that me Windows locale is in French, would it have any impact?

**Comment by nunonup** [comment]
![capturar](https://cloud.githubusercontent.com/assets/19309291/15614626/d16fe8ac-2431-11e6-9ba1-a02867b9d10d.JPG)
Do you install vc_redist.x64.exe?

**Comment by Dunge** [comment]
Sorry for the delay. Yes I have them installed:
![redist](https://cloud.githubusercontent.com/assets/6548184/15677578/5ea20db2-273a-11e6-951a-0d538e798b36.png)

Here's what I got:
![openalpr](https://cloud.githubusercontent.com/assets/6548184/15677639/a51a359e-273a-11e6-89d2-a50278d8748f.png)

Same thing with the windemo application, nothing get matched:
![windemo](https://cloud.githubusercontent.com/assets/6548184/15677682/d50cc65e-273a-11e6-822d-4e91e6916e7f.png)

I also tried setting everything on my computer as US English, no dice. Using Win7 x64 Pro.

**Comment by juandiago** [comment]
@Dunge Did you manage to get it to work?? I'm having the same problem with v2.3.0 and losing my mind here.....

**Comment by Dunge** [comment]
No sorry, haven't touched that since my last post here and I never managed to get it working.
