### ISSUE TITLE
does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by ghpass** [openalpr/openalpr#362]
There is no CMakeLists.txt  file in the openalpr main directory. Why?
I downloded the alpr by running "git clone https://github.com/openalpr/openalpr.git".
According to the document ,  CMakeLists.txt  should be modified. What described in the doc is as follows:
   "
    8.update CMakeLists.txt compile openalpr
   •cd /usr/local/src/openalpr/openalpr/
   •gedit CMakeLists.txt &
   •SET(OpenCV_DIR “/usr/local/lib”)
   •SET(Tesseract_DIR “/usr/local/src/openalpr/tesseract-ocr”)
   •cmake ./
   •make
 "
BTW, the os is linux.
Would you please tell me how to do next? Thanks.

**Comment by matthill** [comment]
The file is in src/CMakeLists.txt
