### ISSUE TITLE
issue in changing package name 

### ISSUE THREAD

**Issue by Aman91Goyal** [openalpr/openalpr#363]
hi,

i have implemented OPEN ALPR library. its working fine. but i need to change the package name but i am not able to change it. because JNI files are configured with package name. If directly i am changing it i am getting issue in initializing open alpr. 

Please suggest me how i can change the package name.

TIA.

**Comment by matthill** [comment]
You can change the package name.  You'll need to update the JNI bindings and recompile the JNI interface DLL.  There are some good resources for JNI here: https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html

**Comment by Aman91Goyal** [comment]
Hi Matthill ,

Thank you for your ans.

I have created .so files for a demo project.

We need .cpp file for creating .so files. Can you please provide the link for .cpp files. That will be more help full for me.


TIA.
