### ISSUE TITLE
Pre-compiled Windows binaries crash

### ISSUE THREAD

**Issue by 6mian** [openalpr/openalpr#371]
Hi, first of all thank you for making this project publicly available. 

I created an empty VS14 project, added the openALPR header, library and DLL from openalpr-2.2.0-win-64bit.zip. It compiles but as soon as I create an alpr::Alpr instance the application crashes:

![af31be8983b1492092dd01f7f9f845e5](https://cloud.githubusercontent.com/assets/19990495/16144122/4fd24c36-3471-11e6-9836-37168540f91e.png)
 
I tried the 32bit version as well, I'm 100% sure I've runtime_data folder and the .conf file at the right places and build target is set properly.

Is there anything else I could try to make this work? Thanks!

**Comment by matthill** [comment]
Can you paste your code?  The path is cropped in the image, so I can't see if that's right.

**Comment by 6mian** [comment]
Hi Matt,

sure, here you go:

```
#include "stdafx.h"
#include "alpr.h"

int main()
{
	alpr::Alpr openalpr("us", "c:\\Users\\i\\Documents\\Visual Studio 2015\\Projects\\ConsoleApplication2\\ConsoleApplication2\\openalpr.conf");
    return 0;
}
```

The openalpr.conf file is exactly at this location and it's the unmodified version from the zip release.
Thanks!

**Comment by matthill** [comment]
There's a paremeter for "runtime_data" in the openalpr.conf: https://github.com/openalpr/openalpr/blob/master/config/openalpr.conf.defaults#L3

Has that been changed?  If not, perhaps try modifying it to an absolute path.

**Comment by 6mian** [comment]
Modyfing the ```runtime_data``` parameter helped, thanks!
I was able to build both 32- i and 64-bit release versions that run without crash on alpr::Alpr initialization. But the debug ones still crashes.

Is there a way to obtain the windows binaries for debug other than building the whole library by myself?

**Comment by matthill** [comment]
The precompiled libraries are currently compiled for release only.  That's a great suggestion for next release.

**Comment by 6mian** [comment]
sorry for late answer: definitely debug version would be useful in future releases, compiling the project under windows is really complicared. Thanks!

**Comment by romeller** [comment]
please notify that precompiled libraries can compile for Release purpose in Visual Studio
on the release page (github.com/openalpr/openalpr/releases)
..because i was stuck when compiled with Debug mode and saw unhandled exception
