### ISSUE TITLE
Error in OpenALPR (Java project / Ubuntu)

### ISSUE THREAD

**Issue by VSecur** [openalpr/openalpr#378]
I always got the following exception when trying to recognize a plate in Ubuntu:

``` Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: no libopenalprjni in java.library.path ```

The same code works perfectly in Windows.

**Comment by matthill** [comment]
You need to make sure OpenALPR libraries are available on your path.  Here's an article that may help:
http://stackoverflow.com/questions/1403788/java-lang-unsatisfiedlinkerror-no-dll-in-java-library-path
