### ISSUE TITLE
How to save JSON to .CSV or TXT file on OpenALPR ?

### ISSUE THREAD

**Issue by junasicpark** [openalpr/openalpr#380]
Hi Master! 

I have a problem with my project openalpr

i already succesfully install Openalpr on my raspberry pi 3 with my raspicam and it works with command " alpr webcam".

now i need help how to save a JSON data from alpr to .CSV or .TXT file on raspi ?

i already try this command : "alpr -j webcam" and "alpr -j webcam Documents/example.txt"
but the data or database JSON wont appear 

so how to fix it ?

on command "alprd -f" it not works on my raspberry pi

**Comment by vladimirr0708982** [comment]
you can use alprd -c eu webcam -j >example.txt

**Comment by junasicpark** [comment]
command alprd not works on my alpr

so if i used command alpr how fix it ?


2016-07-18 2:34 GMT-07:00 vladimirr0708982 <notifications@github.com>:

**Comment by borcherta** [comment]
@junasicpark 
how did you get the picamera to work? Which tutorial did you use?

Thanks
.axel

**Comment by matthill** [comment]
I think Vladimir meant the "alpr" command.  ./alpr -j will output JSON data for each frame.  The > symbol redirects the output to a file.

If you're using alprd, the data is put into a beanstalkd queue named "alprd" You can pull from this queue using a beanstalkd library and write to a txt/csv file.
