### ISSUE TITLE
openalpr-net 129 frames limits

### ISSUE THREAD

**Issue by Hupiter** [openalpr/openalpr#385]
Hello Matt
    I'm using your openalpr-net library on .net project and when I use Alprnet.Recognize((Bitmap)Picture); seems to work perfect but after exactly 129 frames the library just stop recognizing. So is this some kind of buffer problems on the library or I'm doing something wrong?

**Comment by matthill** [comment]
Haven't heard of that before....  Any more details would help.  perhaps upload a sample project to GitHub?

**Comment by Hupiter** [comment]
matt sorry bro, I was building the little example project and i found that the library is working so I need to review my code, thanks for everything.

**Comment by Akshaysharma29** [comment]
@Hupiter does there exist some limitation on its usage?
