### ISSUE TITLE
Help getting the image only license plate from full image

### ISSUE THREAD

**Issue by anhlt309** [openalpr/openalpr#386]
Hi admin,

Firstly, I put an image or video to alpr, then alpr output license plate by string. I want to get the image only license plate region. How to do that with alpr?

**Comment by newsages** [comment]
you have:

 cv::Rect rect = cv::Rect(plate.plate_points[0].x , plate.plate_points[0].y,
                                                     plate.plate_points[2].x - plate.plate_points[0].x,
                                                     plate.plate_points[2].y - plate.plate_points[0].y);
