### ISSUE TITLE
Does openalpr work with opencv 3.1.0

### ISSUE THREAD

**Issue by anhlt309** [openalpr/openalpr#391]
Hi,

I'm using cuda detector to recognize plate. But when I set COMPILE_GPU=1, the building show error: Cannot open include file: 'opencv2/gpu/gpu.hpp'. And i know from version 3.0, opencv was redesigned. I dont know the latest openalpr support opencv 3.1?

Thanks!

**Comment by matthill** [comment]
Yes, it works with OpenCV 3.1.  You need to compile OpenCV w/ CUDA support if you wish to use "COMPILE_GPU".  There are cmake params you need to pass in to turn on CUDA plus you need to have the CUDA libs/includes installed on your system.
