### ISSUE TITLE
Setup Docker service on Github

### ISSUE THREAD

**Issue by kaihendry** [openalpr/openalpr#397]
I've noticed https://hub.docker.com/r/openalpr/openalpr/ has never been pushed to. I suspect you haven't enabled the Docker service in the github repository settings. Thanks!

**Comment by matthill** [comment]
Thanks, Kai.  That's a great idea.  I may setup automation myself to auto-build the Dockerfile on each release.  I've been using Docker a lot lately, and I really like it.  I think we can do a lot more with it for OpenALPR (e.g., a container for alprd and the CLI binary).

**Comment by matthill** [comment]
This should now be active
