### ISSUE TITLE
Ubuntu 16.04 warning

### ISSUE THREAD

**Issue by Izopi4a** [openalpr/openalpr#403]
Hi i got this warning when i apt-get update

W: http://deb.openalpr.com/master/dists/openalpr/InRelease: Signature by key xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx uses weak digest algorithm (SHA1)

**Comment by matthill** [comment]
For 16.04 you no longer need to connect to our repo for the software.  OpenALPR is now in the Debian and Ubuntu standard repositories.  So, just remove that line and reinstall and you should be all set.  I will update the documentation on the GitHub site to reflect that.
