### ISSUE TITLE
Could not load file or assembly in ASPNET

### ISSUE THREAD

**Issue by sirfilipef** [openalpr/openalpr#406]
Could not load file or assembly 'openalpr-net.DLL' or one of its dependencies. The specified module could not be found.

**Comment by matthill** [comment]
This is usually an issue w/ the location of the OpenALPR native DLLs.  The openalpr-net dll needs to be able to find them.

If you search the forums, there's a number of conversations related to this, with some successful outcomes:
https://groups.google.com/forum/#!searchin/openalpr/Could$20not$20load$20file$20or$20assembly%7Csort:relevance
