### ISSUE TITLE
Current opencv has google play security issue with libpng

### ISSUE THREAD

**Issue by diarmuidryan** [openalpr/openalpr#409]
Hi, the version of opencv references libpng version that has vuln on google play preventing publish of app with openalpr. From what i have read using opencv 3.1 fixes this issue, would be great if this could be updated with the new jniLib please.

**Comment by matthill** [comment]
The software supports OpenCV 3.1.  What distribution of the jniLib do you mean?

**Comment by diarmuidryan** [comment]
Hi Matthill, I am unsure, I am using the jniLib that came from this github resource.
The following message is from Google Play, it states libpng as issue which i narrrowed down to be contained in opencv.

can you recommend what version/how i can upgrade opencv within openalpr in android studio? perhaps there are links to articles for others facing similar issue?
google play have gone real tight on any little vuln thesedays :/

**Comment by matthill** [comment]
OpenCV has instructions for compiling on Android NDK.  They officially support it in their build scripts, so it's a pretty painless process.

**Comment by diarmuidryan** [comment]
thanks matt, i'll give that a go
