### ISSUE TITLE
OpenALPR in Python/openalpr

### ISSUE THREAD

**Issue by RadicalHighFives** [openalpr/openalpr#411]
I have openalpr installed on my raspberry pi 2 board. I am having trouble just compiling the first two lines of code. I have the runtime_data folder, openalpr.conf.defaults and libopenalpr.so in build/bin folder within opencv. The error I'm getting is this error: 
Traceback (most recent call last):
File "./...py", line 2 in <module>
    from openalpr import Alpr
ImportError: No module named openalpr

I tried sudo apt-get install python-openalpr. That doesn't seem to work either that error is this:
E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem.

Any help would be appreciated thanks again!

**Comment by matthill** [comment]
That error message is a generic error in Ubuntu (it could happen to any of the packages not just OpenALPR).  Here's a SO article that may help you:
http://askubuntu.com/questions/163200/e-dpkg-was-interrupted-run-sudo-dpkg-configure-a
