### ISSUE TITLE
libdc error when running docker container

### ISSUE THREAD

**Issue by leostarcevic** [openalpr/openalpr#413]
libdc1394 error: Failed to initialize libdc1394
No license plates found.

**Comment by igor-lemon** [comment]
@leostarcevic What did you do ? I have the same problem.

**Comment by dolber** [comment]
If You add -v /dev/null:/dev/raw1394  to docker - Seem's this fixes your problem 

docker run -it --rm -v $(pwd):/data:ro -v /dev/null:/dev/raw1394 openalpr -c eu   h786poj.jpg
