### ISSUE TITLE
vertical shift

### ISSUE THREAD

**Issue by andrey82k** [openalpr/openalpr#427]
Thank you for a very configurable program!
When I'm trying to recognize Russian plate numbers, central letters are cropped. I think that is't because of the last thee digits are a bit higher than the first letter. How cat it be solved by config options?

[ru.conf.txt](https://github.com/openalpr/openalpr/files/616553/ru.conf.txt)

![2016-11-28-170419_1920x1080](https://cloud.githubusercontent.com/assets/3457207/20671209/7c6558a4-b58d-11e6-8478-37109eb8a785.png)

**Comment by matthill** [comment]
Did you figure this out?

You're right, the segmentation stage crops the characters assuming they're all in an even line (no subscript/superscript).  You see the "Winning Lines" debug box is what dictates the crop.  You should be able to fix this by cropping based on the plate edges, or using the top Y and bottom Y for the winning lines to do the crop.  Russian plates are clear white-on-black, so it should be fine to change the cropping to be more forgiving.

**Comment by andrey82k** [comment]
Yes, I solved this =) Thank you for a quick reply and sorry for disturbing you.
I've dug the code, trying to make winning lines parallel, but I'm not a C++ programmer. Finally I succeeded  the correct crop using the following config file: [ru.conf.txt](https://github.com/openalpr/openalpr/files/622616/ru.conf.txt)

Thank you for you work again! You are making a very good thing!

![2016-11-30-211335_1920x1080](https://cloud.githubusercontent.com/assets/3457207/20765353/fd72a3c8-b742-11e6-8c4f-d786747d3561.png)

**Comment by serchch** [comment]
Hi @andrey82k, I try to recognize the russian plates using openalpr. Thank you for the config, you uploaded. It was very helpful. I am using leu as ocr-language, while the language you used was lru in config file. Have you trained the OCR and generate lru or leu would be ok? Thank you in advance.
