### ISSUE TITLE
error when compiling main.cpp in the src directory

### ISSUE THREAD

**Issue by MHKani** [openalpr/openalpr#429]
Hi, when I am compiling the file main.cpp with "g++ -o output1 main.cpp `pkg-config opencv --cflags --libs`
 I have the following errors. Could you please help me how can I compile the file main.cpp? 

main.cpp:(.text+0xb1): undefined reference to `alpr::Alpr::getVersion[abi:cxx11]()'
main.cpp:(.text+0x11e7): undefined reference to `alpr::Alpr::Alpr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x123a): undefined reference to `alpr::Alpr::setTopN(int)'
main.cpp:(.text+0x1252): undefined reference to `alpr::Alpr::getConfig()'
main.cpp:(.text+0x125f): undefined reference to `alpr::Config::setDebug(bool)'
main.cpp:(.text+0x1280): undefined reference to `alpr::Alpr::setDetectRegion(bool)'
main.cpp:(.text+0x12be): undefined reference to `alpr::Alpr::setDefaultRegion(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
main.cpp:(.text+0x12dc): undefined reference to `alpr::Alpr::isLoaded()'
main.cpp:(.text+0x15d9): undefined reference to `alpr::fileExists(char const*)'
main.cpp:(.text+0x1738): undefined reference to `alpr::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x176e): undefined reference to `alpr::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x189e): undefined reference to `alpr::MotionDetector::ResetMotionDetection(cv::Mat*)'
main.cpp:(.text+0x193e): undefined reference to `alpr::sleep_ms(int)'
main.cpp:(.text+0x19d0): undefined reference to `alpr::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1a23): undefined reference to `alpr::startsWith(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1aa7): undefined reference to `VideoBuffer::VideoBuffer()'
main.cpp:(.text+0x1ade): undefined reference to `VideoBuffer::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)'
main.cpp:(.text+0x1b3a): undefined reference to `VideoBuffer::getLatestFrame(cv::Mat*, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&)'
main.cpp:(.text+0x1b6a): undefined reference to `alpr::MotionDetector::ResetMotionDetection(cv::Mat*)'
main.cpp:(.text+0x1c0a): undefined reference to `alpr::sleep_ms(int)'
main.cpp:(.text+0x1c34): undefined reference to `VideoBuffer::disconnect()'
main.cpp:(.text+0x1c6e): undefined reference to `VideoBuffer::~VideoBuffer()'
main.cpp:(.text+0x1d1e): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1d79): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1dd4): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1e30): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x1e8c): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cc39jfYV.o:main.cpp:(.text+0x1ee8): more undefined references to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
/tmp/cc39jfYV.o: In function `main':
main.cpp:(.text+0x20ae): undefined reference to `alpr::fileExists(char const*)'
main.cpp:(.text+0x2183): undefined reference to `alpr::MotionDetector::ResetMotionDetection(cv::Mat*)'
main.cpp:(.text+0x2223): undefined reference to `alpr::sleep_ms(int)'
main.cpp:(.text+0x22d1): undefined reference to `alpr::fileExists(char const*)'
main.cpp:(.text+0x244d): undefined reference to `alpr::DirectoryExists(char const*)'
main.cpp:(.text+0x2479): undefined reference to `alpr::getFilesInDir[abi:cxx11](char const*)'
main.cpp:(.text+0x249f): undefined reference to `alpr::stringCompare(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x2787): undefined reference to `alpr::Alpr::~Alpr()'
main.cpp:(.text+0x3367): undefined reference to `alpr::Alpr::~Alpr()'
main.cpp:(.text+0x338f): undefined reference to `alpr::Alpr::~Alpr()'
main.cpp:(.text+0x33b7): undefined reference to `alpr::Alpr::~Alpr()'
main.cpp:(.text+0x362e): undefined reference to `VideoBuffer::~VideoBuffer()'
main.cpp:(.text+0x3970): undefined reference to `alpr::Alpr::~Alpr()'
/tmp/cc39jfYV.o: In function `is_supported_image(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
main.cpp:(.text+0x3b95): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x3bef): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x3c4a): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x3ca6): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
main.cpp:(.text+0x3cfc): undefined reference to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/cc39jfYV.o:main.cpp:(.text+0x3d4e): more undefined references to `alpr::hasEndingInsensitive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
/tmp/cc39jfYV.o: In function `detectandshow(alpr::Alpr*, cv::Mat, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)':
main.cpp:(.text+0x401d): undefined reference to `alpr::getTimeMonotonic(timespec*)'
main.cpp:(.text+0x4052): undefined reference to `alpr::MotionDetector::MotionDetect(cv::Mat*)'
main.cpp:(.text+0x4190): undefined reference to `alpr::Alpr::recognize(unsigned char*, int, int, int, std::vector<alpr::AlprRegionOfInterest, std::allocator<alpr::AlprRegionOfInterest> >)'
main.cpp:(.text+0x41da): undefined reference to `alpr::getTimeMonotonic(timespec*)'
main.cpp:(.text+0x4201): undefined reference to `alpr::diffclock(timespec, timespec)'
main.cpp:(.text+0x429a): undefined reference to `alpr::Alpr::toJson[abi:cxx11](alpr::AlprResults)'
/tmp/cc39jfYV.o: In function `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x48f3): undefined reference to `alpr::MotionDetector::MotionDetector()'
main.cpp:(.text+0x4902): undefined reference to `alpr::MotionDetector::~MotionDetector()'
collect2: error: ld returned 1 exit status

**Comment by MHKani** [comment]
moreover when I use the command "g++ -o output1 main.cpp `pkg-config opencv openalpr --cflags --libs`" I have the following errors:

/tmp/ccq9YAwb.o: In function `main':
main.cpp:(.text+0x1aa7): undefined reference to `VideoBuffer::VideoBuffer()'
main.cpp:(.text+0x1ade): undefined reference to `VideoBuffer::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)'
main.cpp:(.text+0x1b3a): undefined reference to `VideoBuffer::getLatestFrame(cv::Mat*, std::vector<cv::Rect_<int>, std::allocator<cv::Rect_<int> > >&)'
main.cpp:(.text+0x1c34): undefined reference to `VideoBuffer::disconnect()'
main.cpp:(.text+0x1c6e): undefined reference to `VideoBuffer::~VideoBuffer()'
main.cpp:(.text+0x362e): undefined reference to `VideoBuffer::~VideoBuffer()'
collect2: error: ld returned 1 exit status

**Comment by matthill** [comment]
It looks like your program has found the openalpr headers but is not linking.  Undefined reference means that it doesn't have a binary to match the functions.

**Comment by MHKani** [comment]
Thank you for your help. Now I have another question and I would greatly appreciate it if you help me. I precisely read the instruction of training OCR and the detector. Now I want to know that for a license plate that have two parts, one part with two rows and one part with a single row. For such a license plate, What should I do more than the instruction guide of training OCR and the detector in order to have good results?
The sample of license plate is as the following image. [http://www.licenseplatemania.com/fotos/syrie/syrie1.jpg](url)
Thank you

**Comment by chandr33** [comment]
@MHKani what did you do to solve the problem? I'm having the same difficulty.

Thanks,
Rochak

**Comment by rsingh2083** [comment]
> It looks like your program has found the openalpr headers but is not linking. Undefined reference means that it doesn't have a binary to match the functions.

But how to solve it ?
