### ISSUE TITLE
Showing the detected region/Image C#

### ISSUE THREAD

**Issue by dawigak** [openalpr/openalpr#433]
Hello,

How can i draw a square around the plate on C# binding?

Thank you

**Comment by jovargas** [comment]
Taking `frame` as the image where the plate was detected:

`public void DrawPlateRectangle(Bitmap _frame, Rectangle plateRectangle)`
`{` 
`using(Graphics g = Graphics.FromImage(_frame))`
`using (Pen pen = new Pen(Color.Magenta, 5)`
   `{`
	   `g.DrawRectangle(pen, plateRectangle);`
   `}`
//At this line, `_frame` contains a 5px borders magenta rectangle representing the detected plate.
`}`

//This is a `List<Point>` to `Rectangle` converter.
`public Rectangle boundingRectangle(List<Point> points)`
   ` {`
	`var minX = points.Min(p => p.X);`
	`var minY = points.Min(p => p.Y);`
	`var maxX = points.Max(p => p.X);`
	`var maxY = points.Max(p => p.Y);`
`return new Rectangle(new Point(minX, minY), new Size(maxX - minX, maxY - minY));`
    `}`

//And you can use them like this:
`var results = alpr.Recognize(frame);`
`if (results.Plates.Count() > 0)`
`{`
`foreach (var result in results.Plates)`
`{`
`var rect = boundingRectangle(result.PlatePoints);`
`DrawPlateRectangle(frame, rect);`
`}`
`}`

**Comment by jovargas** [comment]
Please, close this topic as does not make reference to an issue.

There is a forum for questions like this: https://groups.google.com/forum/#!forum/openalpr

**Comment by ivanh23** [comment]
Hello . i tried your example and it dont work , can you help me ?

**Comment by rogeriocpe** [comment]
Boa tarde a todos, estou iniciando com openalpr e tenho muita dificuldade para mostar o retangulo de localização da placa, alguem poderia me ajudar. Como posso implementar neste código?

Segue meu código:

class Program
    {
        static void Main(string[] args)
        {
            var alpr = new AlprNet("br", "C:/OpenALPR/openalpr_64/openalpr.conf", "C:/OpenALPR/openalpr_64/runtime_data");
            if (!alpr.IsLoaded())
            {
                Console.WriteLine("OpenAlpr failed to load!");
                return;
            }
            // Aplique opcionalmente a correspondência de padrões para uma região específica
            alpr.DefaultRegion = "sp";

            var imageLocal = ("C:/OpenALPR/openalpr_64/placas/03.jpg");
            var results = alpr.Recognize(imageLocal);
            int i = 0;
            foreach (var result in results.Plates)
            {
                Console.WriteLine("Plate {0}: {1} result(s)", i++, result.TopNPlates.Count);
                Console.WriteLine("  Processing Time: {0} msec(s)", result.ProcessingTimeMs);
                foreach (var plate in result.TopNPlates)
                {
                    Console.WriteLine("  Placa - {0}\t Confidence: {1}\tMatches Template: {2}", plate.Characters,
                                      plate.OverallConfidence, plate.MatchesTemplate);
                    

                }
                
            }
            

        }
    }

**Comment by rogeriocpe** [comment]
Good afternoon everyone, I'm starting with openalpr and I have a hard time showing the rectangle of the location of the plate, someone could help me. How can I implement this code?

Here is my code:
class Program
{
static void Main(string[] args)
{
var alpr = new AlprNet("br", "C:/OpenALPR/openalpr_64/openalpr.conf", "C:/OpenALPR/openalpr_64/runtime_data");
if (!alpr.IsLoaded())
{
Console.WriteLine("OpenAlpr failed to load!");
return;
}
// Aplique opcionalmente a correspondência de padrões para uma região específica
alpr.DefaultRegion = "sp";

        var imageLocal = ("C:/OpenALPR/openalpr_64/placas/03.jpg");
        var results = alpr.Recognize(imageLocal);
        int i = 0;
        foreach (var result in results.Plates)
        {
            Console.WriteLine("Plate {0}: {1} result(s)", i++, result.TopNPlates.Count);
            Console.WriteLine("  Processing Time: {0} msec(s)", result.ProcessingTimeMs);
            foreach (var plate in result.TopNPlates)
            {
                Console.WriteLine("  Placa - {0}\t Confidence: {1}\tMatches Template: {2}", plate.Characters,
                                  plate.OverallConfidence, plate.MatchesTemplate);
                

            }
            
        }
        

    }
}
