### ISSUE TITLE
openalpr compile issue, gcc-4.8.5

### ISSUE THREAD

**Issue by anugrahasinha** [openalpr/openalpr#434]
compilation of openalpr is failing on gcc-4.8.5
Error message
`Building CXX object misc_utilities/CMakeFiles/openalpr-utils-benchmark.dir/benchmarks/benchmark.cpp.o
In file included from /usr/include/c++/4.8.2/atomic:38:0,
                 from /usr/include/log4cplus/helpers/pointer.h:43,
                 from /usr/include/log4cplus/appender.h:36,
                 from /usr/include/log4cplus/spi/appenderattachable.h:33,
                 from /usr/include/log4cplus/logger.h:36,
                 from /home/asinha/work/openalpr_compile/BUILD/openalpr/src/video/logging_videobuffer.h:5,
                 from /home/asinha/work/openalpr_compile/BUILD/openalpr/src/daemon.cpp:8:
/usr/include/c++/4.8.2/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
`

Also shown
`/usr/include/c++/4.8.2/bits/atomic_base.h:70:3: note: C++11 'constexpr' only available with -std=c++11 or -std=gnu++11
/usr/include/c++/4.8.2/bits/atomic_base.h:76:3: error: 'constexpr' does not name a type
   constexpr memory_order
`

And more of such.

Details about system:
`[asinha@hydra-linux-dev1 openalpr_compile]$ uname -a
Linux hydra-linux-dev1 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[asinha@hydra-linux-dev1 openalpr_compile]$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
`

Strangely it compiled correctly on an ARM-32bit Raspi OS.

**Comment by matthill** [comment]
I'm guessing the version of log4cplus that you're linking against was compiled with C++11... So you either need to do the same for OpenALPR or recompile log4cplus without.

**Comment by anugrahasinha** [comment]
I recompiled log4cplus without C++11, and openalpr compilation worked.

**Comment by merimem** [comment]
Hello, 
I have the same problem as you, how can I recompile log4cplus without C++11 please?

Thank you in advance.
