### ISSUE TITLE
Read image from URL?

### ISSUE THREAD

**Issue by devhaoy** [openalpr/openalpr#439]
Quick question, can the path be a URL or does it have to be a disk path?

**Comment by matthill** [comment]
It has to be a disk path.  The CLI utility assumes that a URL is an MJPG video stream https://github.com/openalpr/openalpr/blob/master/src/main.cpp#L212

**Comment by devhaoy** [comment]
Thanks for you answer! 
Pretty sure there is a big case at supporting url for jpeg / png. Anyone has a way around please let me know!

**Comment by matthill** [comment]
You can modify the main.cpp code to pull the image and send the bytes to OpenALPR.  It should be a fairly straightforward change.
