### ISSUE TITLE
Node js - Request post to cloud api getting error 400 missing tasks

### ISSUE THREAD

**Issue by devhaoy** [openalpr/openalpr#440]
Hi,
I am trying to make a post requuest to the API with this code:

```
  request.post(
    'https://api.openalpr.com/v1/recognize',
    { secret_key:'itsmysecret',
      tasks :"plate",
      image:'/tmp/MYIMAGE.jpg',
      image_url: receivedImageUrl,
      country: "us" },
    function (error, response, body) {
        if (error) throw error
        else {
            console.log(JSON.stringify(body, null, 2));
        }
    });
```

First I am trying to make this work as a stand alone, is it possible?

The body shows` {\"error_code\": 400, \"error\": \"Missing tasks\"}"` , is there something I am missing?

**Comment by matthill** [comment]
Try sending the options as query strings.  For example:
  request.post(
    'https://api.openalpr.com/v1/recognize?secret_key=itsmysecret&tasks=plate&image_url=[url]&country=us',
    function (error, response, body) {
        if (error) throw error
        else {
            console.log(JSON.stringify(body, null, 2));
        }
    });

For the image it can be one of the following
- an image url (e.g., http://www.google.com/logo.png)
- a base64 image (use image_bytes)
- an image sent as form_data

**Comment by devhaoy** [comment]
HI Mat and thanks for that! I could get the JSON following your advice, although for some reason the `plate` results array is always empty, while `color` and `make` are working. No idea why.

Would you snippet the code on how to send my image as form_data? I am surely misusing Request's form_data feature here, as I get `{\"error_code\": 400, \"error\": \"Unable to download image\"}"` in my logs. I don't know how to append the params + data_form

```
var request = require('request'); 
var fs = require('fs'); 

var receivedImageUrl = 'https://scontent.xx.fbcdn.net/v/t35.0-12/16129296_10211776220218012_1068483829_o.jpg?_nc_ad=z-m&oh=efe36c45800eaf57449cf0ed6b9d527a&oe=5884525F';
var download = function(uri, filename, callback){
  request.head(uri, function(err, res, body){
  	request(uri).pipe(fs.createWriteStream(filename)).on('close', callback);
  });
};

download(receivedImageUrl, '/tmp/MYIMAGE.jpeg', function(body) {
	var req = request.post('https://api.openalpr.com/v1/recognize?secret_key=itsmysecret&tasks=plate&country=us&image=', function (err, resp, body) {
		if (err) throw err;
		console.log('URL: ' + body);
});
	var form = req.form();
	form.append('file', fs.createReadStream('/tmp/MYIMAGE.jpeg'));
});


```

**Comment by devhaoy** [comment]
My other option is to send a base64 image but i get an error `Request-URI Too Large`

```
function base64_encode(file) {
    // read binary data
    var bitmap = fs.readFileSync(file);
    // convert binary data to base64 encoded string
    return new Buffer(bitmap).toString('base64');
}

download(receivedImageUrl, '/tmp/MYIMAGE.jpeg', function(body){
var base64str = base64_encode('/tmp/MYIMAGE.jpeg');
request.post(
    'https://api.openalpr.com/v1/recognize?secret_key=sk_e25adf7a0ab3ef5512e004e7&tasks=color,plate&image_bytes=' + base64str + '&country=fr',
 function (error, response, body) {
 	if (error) throw error;
    console.log(JSON.stringify(body, null, 2));
    });
});
```

**Comment by marek-veber** [comment]
please see for example:
http://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be

and post image as a data of http-POST request, not in url ;)

**Comment by devhaoy** [comment]
Thanks @marek-veber i hit that thread earlier today, and surely I'm doing things wrong.does  POSTing the image as data simply means I should set binary to true?

**Comment by matthill** [comment]
You'll want to send the "image_bytes" parameter as a POST.  The value should just be your image data directly encoded in base64.  It's slightly more efficient to send the image as a file using POST (file name should be "image")

**Comment by devhaoy** [comment]
Thanks for your help! I could finally handle the post request with form data. For any noob like me bumping into this problem, here how to handle a form data post request

```
var request = require('request'); 
var fs = require('fs'); 

var formData = {
  secret_key:'MY_SECRET',
  image: fs.createReadStream('/tmp/MYIMAGE.jpeg'),
  tasks:'plate',
  country:'fr'
};
 
request.post({url:'https://api.openalpr.com/v1/recognize', formData: formData }, function(err, httpResponse, body) {
  if (err) {
    return console.error('upload failed:', err);
  }
  console.log(formData);
  console.log('Upload successful!  Server responded with:', body);
});

```

Still I cannot get the `plate` results (empty array) while `color` and `make` work fine. Please advise if you know of this issue!

**Comment by Durgaprasad525** [comment]
@TheDApact  unable to get color and body type of the image when using nodejs. Any Idea?
