### ISSUE TITLE
Maximum characters for processing

### ISSUE THREAD

**Issue by ramyabp** [openalpr/openalpr#441]
Hi,

I am working on Openalpr. I want to change postProcessMaxCharacters value.Changing which, I am not seeing difference in the postprocess data.

Please let me know if am missing anything.

Thanks in advance,
Ramya

**Comment by matthill** [comment]
When you change the config to something smaller (e.g., 6 characters) are you still seeing output with more than 6 characters?

**Comment by ramyabp** [comment]
Even if I do something smaller,am seeing more than the configured characters. It is always taking 8 characters as maximum for Europe.

**Comment by ramyabp** [comment]
Able to proceed in this, so closing the same
