### ISSUE TITLE
couts of postprocessor and text detection

### ISSUE THREAD

**Issue by ramyabp** [openalpr/openalpr#443]
Hi,

I have introduced my own couts inside the debug code in postprocessor. It is so weird that it gets compiled but NO prints. Earlier debugs are found.[Fn:PostProcess::analyze()].

I have tried replacing libraries too.Please let me know what am missing.

Thanks,
Ramya

**Comment by matthill** [comment]
I don't see any reason why that wouldn't work.  Are you sure your binary is using the openalpr library you compiled?  Running ldd [binary] will show you the libs it's linked against.

**Comment by ramyabp** [comment]
The timestamp change happens for the binaries and libraries too. If I introduce a compiler error, it is able to detect the same.

Thanks,
Ramya
