### ISSUE TITLE
Cloud API gives me different (better) results

### ISSUE THREAD

**Issue by jonflanders** [openalpr/openalpr#445]
Hi - I am evaluating openalpr for a project (not license plate based but similar in terms of identifying a sequence of numbers in a rectangle from a photo).

I am getting great results when I submit a photo to your cloud test page.

I am getting ok results when I run the same picture locally through the command line or the API.

Are there settings on the cloud usage of your API that are different than the typical defaults on the command line?

Thanks
Jon

**Comment by matthill** [comment]
Hi Jon,

The Commercial release (which the Cloud API uses) has an improved OCR engine for US plates.  That may account for the better accuracy.
