### ISSUE TITLE
Reliability in different environmental conditions

### ISSUE THREAD

**Issue by ramyabp** [openalpr/openalpr#450]
Hi Matt,
Thanks for answering my earlier queries.Please let me know how openalpr would function in case of rainy,foggy environment.

It would be great help if you could let me know, where and what to look for these conditions.

Thanks,
Ramya

**Comment by matthill** [comment]
As long as the license plate can be clearly seen, you'll have good results.  Rain and fog tends to affect IR cameras more than visible spectrum.  Vehicle headlights shooting into fog will probably make the plates unreadable.
