### ISSUE TITLE
fr.conf not loaded

### ISSUE THREAD

**Issue by throuch** [openalpr/openalpr#470]
It seems that when I invoke _alpr_ with the following parameters:
./alpr -c eu -p fr ...
the config file _fr.conf_ is not loaded, but only _eu.conf_

In the implementation, there must be a confusion between **region** and **country**

**Comment by matthill** [comment]
That is the correct behavior.  "Country" isn't the best name.  It's meant to mean plate style.  Countries in Europe all share a wide-style plate, so "eu.conf" describes that.  The dataset includes training data from all European countries.  The pattern (in eu.patterns) will match the text against French characters.

If you would like to train your own country specific dataset (e.g., just French plates and French OCR) that is possible, and you could name it fr.conf.
