### ISSUE TITLE
Node.js of OpenALPR can't be installed

### ISSUE THREAD

**Issue by kevinjpetersen** [openalpr/openalpr#472]
Today I tried to install OpenALPR using NPM with Node.js, but I keep getting these errors from the picture below.

What I've tried:

- Installing older Node.js versions.
- Installing older Node-openalpr versions.
- Installing 'node-gyp' and 'node-pre-gyp' as NPM Packages
- Using NVM to switch between different combinations of Node.js, NPM and Node-openalpr versions.

None of these works. Is the Node-Openalpr library totally broken?
I see other people has the same issue on it's Github: https://github.com/netPark/node-openalpr/issues

If this doesn't work, and the creator seems to have abandoned the project, shouldn't it be removed?

Can anyone else confirm/de-confirm that this is infact also happening for others?

As a last question. If this can't be fixed, what's an alternative to install 'node-openalpr' manually? Can I do that?

Thanks!

![image](https://cloud.githubusercontent.com/assets/1038017/23582780/aa3b8bae-0132-11e7-81d9-4c9663aabe8f.png)

**Comment by Daniel15** [comment]
What happens if you run the `node-gyp` command manually? See the full command after it says "Failed to execute 'node-gyp.cmd build ........'"
