### ISSUE TITLE
Cannot build classifychars in Ubuntu 16.04

### ISSUE THREAD

**Issue by ilikecats567** [openalpr/openalpr#486]
I downloaded OpenALPR through ["The Easiest Way"](https://github.com/openalpr/openalpr/wiki/Compilation-instructions-(Ubuntu-Linux)) in Ubuntu 16.04, and it installed with all the utilities. However, when I tried to use `classifychars`, the keys don't work. So I re-downloaded OpenALPR, this time the "The Easier Way" so that I could access the source files and change the key mappings to reflect my version of OpenCV, and tried to rebuild `classifychars`, with the following commands:

`cd misc_utilities
cmake .
make`

I end up with the following error:
> /openalpr/src/misc_utilities/benchmarks/benchmark.cpp:29:23: fatal error: alpr_impl.h: No such file or directory
> compilation terminated.

Why can't the program find the libraries? I know I have alpr_impl.h, but it can't see it.

I downloaded OpenALPR in my root folder, btw, `root@my-computer-name`.

Please help!

**Comment by matthill** [comment]
You may need to edit CMakeLists.txt to make sure the include directory (where alpr_impl.h) is available.

**Comment by ilikecats567** [comment]
Hi, 

I rebuilt OpenALPR from scratch, so that solved my problem!
