### ISSUE TITLE
OpenALPR Daemon - POST for each frame

### ISSUE THREAD

**Issue by lschuermann** [openalpr/openalpr#489]
In our current project, we decided to use OpenALPR for recognition of license plates and its working extraordinarily well! Especially useful is the included OpenALPR-Daemon, which we use to push the data to our backend via the integrated JSON-POST feature.

It would be even better, if there was an option to send these POST-requests even if no plate was found in a frame. Then we could easily check how many frames were processed in total and have a live-count. Is this feature of general interest and how easy can something like this be implemented?
I'm guessing, as for the configuration, you could simply add `upload_data = 2` as a mode-switch for this?

Thanks!

**Comment by matthill** [comment]
I'm not sure if it's generally useful, but it could be implemented very easily.  Just move this line of code down 1 line (so that it always writes to the queue whether there are results or not): 
https://github.com/openalpr/openalpr/blob/master/src/daemon.cpp#L329
