### ISSUE TITLE
Current UK Number plate format

### ISSUE THREAD

**Issue by dannytsang** [openalpr/openalpr#495]
Most of the time UK plates with a 1 are recognised as an I. The new (current) default format is:
CCNN CCC
C = character A-Z
N = number from 0-9

The numbers indicate the year and therefore it's a 1 instead of an I. See **New Style Number Identifier** in https://www.nationalnumbers.co.uk/dvla-guide/year-of-issue-149.htm

Either a UK specific or help with adding this to ALPR's analysis would be great.

I've attached the sample image and the output from ALPR
![example](https://cloud.githubusercontent.com/assets/567982/25567272/fb3651ac-2de1-11e7-9a17-c7c6e54b2291.png)
`alpr -c eu -p gb myimage.png`
![alpr output](https://cloud.githubusercontent.com/assets/567982/25567283/2803d79a-2de2-11e7-91d7-c0f1c0b4b938.png)

**Comment by dannytsang** [comment]
Don't worry figured out that the -c parameter should be gb and not eu so:
`alpr -c gb myimage.png`

**Comment by jovargas** [comment]
> Either a UK specific or help with adding this to ALPR's analysis would be great.

That analysis already exists in OpenALPR:
Set `must_match_pattern = 1` in openalpr.conf and use `alpr c- gb -p gb myimage.png`  

Then please open a cold beer and enjoy :)

**Comment by dannytsang** [comment]
Thanks @jovargas Setting the must match pattern reduces the result a lot too.
