### ISSUE TITLE
UK Plate Region pattern matching

### ISSUE THREAD

**Issue by dannytsang** [openalpr/openalpr#496]
Most of the time UK plates with a 1 are recognised as an I. The new (current) default format is:
CCNN CCC
C = character A-Z
N = number from 0-9

The first 2 characters denote the region the car was registered (unless it's a personalised plate).

Could this be added to the pattern matching? A list of the associate regions can be found here:
https://www.newreg.co.uk/dvla-number-plate-identifiers/

**Comment by jovargas** [comment]
Do you mean to add the region identification to OpenALPR? I think it would be easier to make your own script to identify the region once you have OpenALPR result. It should take just a few lines of code. 
Adding that to the source code could be a little tricky, but not impossible if you have time and skills to do it.

**Comment by dannytsang** [comment]
@jovargas I may have misunderstood the pattern matching because the examples were using US states so I thought it was to extract the state information from the number plates. Re-reading it I'm guessing this is to handle the styles of plates in different states?

**Comment by jovargas** [comment]
Pattern matching is only for characters. Region feature is for visual style matching.
