### ISSUE TITLE
How to connect with python openalpr to mjpeg stream?

### ISSUE THREAD

**Issue by N00D13** [openalpr/openalpr#504]
It's an awesome Libary but the Documentation is a little bit small!

I want connect my python openaplr to a mjpeg stream.
How to build that?

**Comment by baramuse** [comment]
You can use the daemon for that.
https://github.com/openalpr/openalpr/wiki/OpenALPR-Daemon-(alprd)

**Comment by alucard079** [comment]
Are you done with this? Are you able to make it work? @N00D13
