### ISSUE TITLE
Support unicode characters

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#53]
Copied from Roya Gh forum post:

I want to add support for plates of a new country to OpenAlpr so that it can recognize the license plates of Iran.
I've tained tesseract for persian and it works for Iimages of Persian text,
but when I try to use OpenAlpr the output is sth like this:

  plate0: 9 results
    - лллллилл     confidence: 83.9618     template_match: 0
    - лллллил     confidence: 81.1455     template_match: 0
    - ллйлллил     confidence: 81.0826     template_match: 0

I've tarined for unicode but I've realized that OpenAlpr doesn't use UTF8, I suppose that the problem is due to this,

const char\* choice = ci.GetUTF8Text();
postProcessor->addLetter(*choice, j, ci.Confidence());

here https://github.com/openalpr/openalpr/blob/master/src/openalpr/ocr.cpp#L104

Is there any implementation of OpenAlpr supporting UTF8?

**Comment by hesamel** [comment]
hi
any body there 
?

**Comment by sthiruppathi** [comment]
Hello Matthill,
Do you have trained configuration file for Indian plates ?

Thanks.!
by
Thiru :)
