### ISSUE TITLE
Reconhecimento formato placa brasil

### ISSUE THREAD

**Issue by AntonioLuizTadeu** [openalpr/openalpr#551]
Boa tarde colegas!

Preciso de uma ajuda.
como  devo usar o arquivo "br.xml" 
e como  corrigir a visualização da licença  de  FED2DI6 quando deveria ser  FED20I6.

Confesso   que não ficou claro onde devo alterar o "Formato"
Criei o arquivo   "br.xml"  e br.patterns    mas, não funcionou, melhor,  nem consegue ler a licença.

![bmw z11](https://user-images.githubusercontent.com/30487304/28748448-b6c2aeb4-748e-11e7-9904-761dcad54c1e.jpg)

obrigado, mais  uma vez.

**Comment by jovargas** [comment]
Duplicate of https://github.com/openalpr/openalpr/issues/124
Veja se lá resolve.
Se ainda precisar de mais ajuda, me contate pelo email: jvargas.eng@gmail.com.

**Comment by usantos** [comment]
Olá!

Dentro do runtime_data adicionei os arquivos br e está retorando este erro:

--(!) Runtime directory '/usr/share/openalpr/runtime_data' is invalid.  Missing OCR data for the country: 'br'!

Alguém já conseguiu detectar as placas br?

**Comment by TurboTux** [comment]
Também estou com essa dificuldade. Não achei nenhum dataset ainda pra treinar o modelo brasileiro, mas acho que especificar @@@-XXXX (segundo a documentação) já ajuda a diminuir os erros de reconhecimento (tipo 0 e O, 1 e I).

Onde acho esse XML?
