### ISSUE TITLE
Failed to open Stream with autentification

### ISSUE THREAD

**Issue by mika-nt28** [openalpr/openalpr#553]
If I used my url camera with http://User:Pass@192.168.0.***:**/videostream.cgi Alprd doesn't work
If I used my url camera with http://192.168.0.***:**/videostream.cgi?user=User&pass=Pass Alprd does work

This two Url worked in my navigator Chrome

**Comment by Azat868** [comment]
Open first stream in VLC player, it is work?

**Comment by Azat868** [comment]
What camera? See your brand camera and stream url: https://www.ispyconnect.com/sources.aspx

**Comment by mika-nt28** [comment]
Hello,

Yes, if i used this url format http://User:Pass@192.168.0.***:**/videostream.cgi, I have a video stream in VLC

This problem has been seen on several camera
