### ISSUE TITLE
alprd stops queuing jobs to beanstalkd

### ISSUE THREAD

**Issue by ff-uwe** [openalpr/openalpr#572]
Hi,

I dont know if it is an issue or not but i cannot find any solution for this the point is alprd sends jobs to beanstalkd and i do receive them in my web app they are signed to database, unfortunately it just stops after a while queuing them there are connections, it starts only when i restart aplrd manually.
I use macos sierra, on linux ubuntu 16.04 lts it works like it should but when i try to run it on mac it stops. From time to time i receive this error:
beanstalkd: prot.c:710 in check_err: read(): Connection reset by pee

anyone had similar experience?   
thanks for any help

**Comment by boomfly** [comment]
+1

**Comment by pawap90** [comment]
I'm experiencing a similar issue. Did you find a solution?
