### ISSUE TITLE
Picture size 0x0 is invalid

### ISSUE THREAD

**Issue by SylarRuby** [openalpr/openalpr#589]
I've installed the software on Ubuntu (In a docker container). The process is, in docker, I install Ubuntu and openALPR. Inside the config file, I added my `rtsp` stream URL: `rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
`

In VLC, stream works fine. Using the command `alprd -f` to start the program, I get

```
root@6e3afedf9157:/# alprd -f
INFO - Running OpenALPR daemon in the foreground.
INFO - Using: /etc/openalpr/alprd.conf for daemon configuration
INFO - Using: /var/lib/openalpr/plateimages/ for storing valid plate images
INFO - country: eu -- config file: /etc/openalpr/openalpr.conf
INFO - Stream 1: rtsp://192.168.1.151:554/cam/realmonitor?channel=1&subtype=1&unicast=true&proto=Onvif
INFO - Starting camera 1
INFO - Video stream connecting...
[IMGUTILS @ 0x7f68612e9640] Picture size 0x0 is invalid
```

However, installing this on Mac (brew), no issues and all works. Could someone give me some sort of clue as to why I get `Picture size 0x0 is invalid`? Few searches say `OpenCV` is to be blamed? I've updated OpenCV and same issue.

**Comment by BahadirGLCK** [comment]
Did you solve? Can you explain if you solved?
