### ISSUE TITLE
openalpr ZA plates

### ISSUE THREAD

**Issue by somejavadev** [openalpr/openalpr#600]
Hi,

Is it possible to create a public openalpr/za_plates repository allowing contributors to upload South African number plates to be trained?

**Comment by chrislpr** [comment]
I think that there are much better solutions out there.  Let me know if you would like to discuss the options.
Regards
Chris

**Comment by DivisionMax** [comment]
@somejavadev Did you get some traction on this at all, whether on GitHub or elsewhere?

**Comment by somejavadev** [comment]
@DivisionMax I got busy on another project but seems that there is no big collaborative effort to get this done specifically for ZA. Seems like people are using a mix of the European plate sets and training their own.

**Comment by ripkk** [comment]
@DivisionMax Would you like to collaborate on getting a data-set going?

**Comment by DivisionMax** [comment]
@ripkk My team and I decided to build our own model, but I'm open to the idea, how do envision this?
