### ISSUE TITLE
Recognize the plate with multiple lines?

### ISSUE THREAD

**Issue by zhouhao27** [openalpr/openalpr#612]
Here is my sample image file.

![sgg7777b](https://user-images.githubusercontent.com/8099731/34705226-ef50e4f4-f539-11e7-8aca-5f499f771113.jpg)

Can't recognize at all.

Another one:

![sft8515c](https://user-images.githubusercontent.com/8099731/34705234-ffadd69a-f539-11e7-9b59-e12066dea96d.jpg)

Can only recognize the second line as 8515C.

What should I do to recognize multiple lines? Thanks.

**Comment by zhouhao27** [comment]
Any suggestion? Thanks.

**Comment by zhouhao27** [comment]
Have to change my conf and train the detector. I managed to make it work although the accuracy is still quite know. I don't know how to improve it.

**Comment by bamwani** [comment]
Hey, @zhouhao27 Any progress? How did you do it finally?
