### ISSUE TITLE
FeatureMatcher → extractor, cv::BRISK caching

### ISSUE THREAD

**Issue by twelve17** [openalpr/openalpr#63]
I am testing openalpr on iOS, and noticed via profiling that a chunk of time (~ 3-5 sec on an iPhone 4S) is spent in [instantiating the cv::BRISK object for the FeatureMatcher extractor](https://github.com/openalpr/openalpr/blob/master/src/openalpr/featurematcher.cpp#L42).  How do you feel about implementing a caching mechanism (serialization?), since it appears that the values for instantiation are static?  Admittedly, I have never done serialization in C++, but I could look into it if you would like.

**Comment by matthill** [comment]
Implemented by twelve17 in commit 3684402d8ba90bbd6ce3e550194ff759cbc56046
