### ISSUE TITLE
make error undefined reference to `log4cplus::Logger::operator=(log4cplus::Logger&&)'

### ISSUE THREAD

**Issue by tensor-flower** [openalpr/openalpr#668]
```
[ 53%] Linking CXX executable alprd
CMakeFiles/alprd.dir/daemon.cpp.o: In function `main':
daemon.cpp:(.text+0xa54): undefined reference to `log4cplus::Logger::operator=(log4cplus::Logger&&)'
daemon.cpp:(.text+0xbce): undefined reference to `log4cplus::Logger::operator=(log4cplus::Logger&&)'
collect2: error: ld returned 1 exit status
CMakeFiles/alprd.dir/build.make:210: recipe for target 'alprd' failed
make[2]: *** [alprd] Error 1
CMakeFiles/Makefile2:69: recipe for target 'CMakeFiles/alprd.dir/all' failed
make[1]: *** [CMakeFiles/alprd.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```
I can cmake but cannot make.

I tried adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` or `set (CMAKE_CXX_STANDARD 11)` to CMakeLists.txt but neither works, can someone please help? :)

**Comment by tensor-flower** [comment]
I figured out the solution. I compiled log4plus from source. Run `./configure CXXFLAGS="-std=c++0x"`

Then I can make alpr already.

**Comment by pawarren** [comment]
@tensor-flower when you compled log4cplus from source, do you remember how you told OpenALPR where to look for the new log4cplus files?

**Comment by tensor-flower** [comment]
If I remember correctly

Once I compile log4cplus from source, I dont have to tell alpr where log4cplus is. Log4cplus is just a logging tool.
