### ISSUE TITLE
Undefined references when trying to build .so files for Android

### ISSUE THREAD

**Issue by TheRealBashkim** [openalpr/openalpr#685]
Hi, I'm trying to compile OpenALPR to be able to pass data in without having to store it as an actual image file. I have been compiling using the windows instruction page on the OpenALPR document site were everything seems to go correctly.

the problem I have is with the libopenalpr-static.a file which I get from compiling.

![image](https://user-images.githubusercontent.com/8060453/41147901-7fe96de8-6aff-11e8-9234-b5809176cbf2.png)

when I try and build the .so files using android ndk-build I get these errors referring to undefined references.

![image](https://user-images.githubusercontent.com/8060453/41148105-0c0af08a-6b00-11e8-9114-f9a0f10d1d5c.png)

Is there anything that I could be missing or is there a step I am missing?
any help pointing me in the right direction would be extremely helpful.

Thanks.

**Comment by marekfoltyn** [comment]
Did you manage to fully integrate OpenALPR in Android? If so, how did you do that? I'm trying for couple of days without success..

**Comment by TheRealBashkim** [comment]
No sorry, I've given up on it.
