### ISSUE TITLE
openalpr can't run with tesseract 4.0.0 version

### ISSUE THREAD

**Issue by engycz** [openalpr/openalpr#691]
Due to change in tesseract https://github.com/tesseract-ocr/tesseract/pull/1356 the path for traineddata is searched in /ocr/xxx.traineddata and not /ocr/tessdata/xxx.traineddata

Ubuntu 18.04 uses tesseract version 4.0.0 so openalpr can't be run on this system.

Similar problem reported here https://github.com/openalpr/openalpr/issues/641

**Comment by jovargas** [comment]
@engycz Thanks for your recent PR. After that, OpenALPR is working fine with Tesseract 4 but still using traineddata from Tesseract 3.XX. Did you get to train a file for Tess4 with lstm engine? I've been trying the new training process but without decent results.

**Comment by logidelic** [comment]
> working fine with Tesseract 4 but still using traineddata from Tesseract 3.XX

@jovargas Isn't Tesseract 4 incompatible with Tesseract 3 traineddata files? Or did you really get that working? Thanks much.
