### ISSUE TITLE
By pass the plate detection

### ISSUE THREAD

**Issue by zhouhao27** [openalpr/openalpr#701]
Based on the openalpr design document, the pipeline stages is:

```
Detection 
Binarization
Char Analysis
Plate Edges 
Deskew 
Character Segmentation
OCR 
Post Processing

```

Since my use case is simpler, I don't need the license plate detection. Because I'm able to manually provide the image for the vehicle plate to openalpr. In this case, can I ignore the detection phrase and start the whole flow from **Binarization**?

**Comment by bradcagle** [comment]
in the openalpr config file is this option

; Bypasses plate detection.  If this is set to 1, the library assumes that each region provided is a likely plate area.
skip_detection = 0

**Comment by zhouhao27** [comment]
@bradcagle Thanks. It works. It helps me to find out that the low accuracy is not because of the region detection. Because even after I ignore the detection, the accuracy is still low for double line vehicle plate. Both single line and double line plate share the same font so that means the OCR part is the same.

**Comment by zhouhao27** [comment]
@bradcagle Actually I have another question. If it possible to let the library return the image data for detected vehicle license plate?
