### ISSUE TITLE
Added country not being recognized

### ISSUE THREAD

**Issue by tajition** [openalpr/openalpr#712]
I added a new country (Mongolia),

Copied the us.conf file and edited it to match Mongolian license plate specifications
I rebuilt the project and tried running it with 
alpr sample.jpeg -c mn 
but I get this error:

Runtime directory '/usr/share/openalpr/runtime_data' is invalid.  Missing OCR data for the country: 'mn'!

I checked the directory and it exists and the mn.conf file is there.

Here is my mn.conf file
; 30-50, 40-60, 50-70, 60-80
char_analysis_min_pct = 0.30
char_analysis_height_range = 0.20
char_analysis_height_step_size = 0.10
char_analysis_height_num_steps = 4

segmentation_min_speckle_height_percent = 0.3
segmentation_min_box_width_px = 4
segmentation_min_charheight_percent = 0.5;
segmentation_max_segment_width_percent_vs_average = 1.35;

plate_width_mm = 520
plate_height_mm = 114

multiline = 0

char_height_mm = 82
char_width_mm = 50
char_whitespace_top_mm = 8
char_whitespace_bot_mm = 8

template_max_width_px = 130
template_max_height_px = 28

; Higher sensitivity means less lines
plateline_sensitivity_vertical = 25
plateline_sensitivity_horizontal = 45

; Regions smaller than this will be disqualified
min_plate_size_width_px = 70
min_plate_size_height_px = 35

; Results with fewer or more characters will be discarded
postprocess_min_characters = 5
postprocess_max_characters = 9

ocr_language = lmn

; Override for postprocess letters/numbers regex. 
postprocess_regex_letters = [А-ЯҮӨ]
postprocess_regex_numbers = [0-9]

; Whether the plate is always dark letters on light background, light letters on dark background, or both
; value can be either always, never, or auto
invert = auto

**Comment by Erffa** [comment]
Did you find a solution to your problem ?

**Comment by ZIKO94ZIKO** [comment]
same problem

**Comment by dhcmega** [comment]
hi, same problem. Is there a solution? thanks!
