### ISSUE TITLE
How to solve 'AlprNet' could not be found?

### ISSUE THREAD

**Issue by bit-scientist** [openalpr/openalpr#720]
I looked for the answers here and there with no luck, so I decided to ask out.
I want to implement this repository on my own PC and I am following [this video][2] to accomplish the task. I have done all the steps he did and at the end, when I tried to build it but, in one of the .cs code there is *CS0246* error that says: 

    Error	CS0246	The type or namespace name 'AlprNet' could not be found (are you missing a using directive or an assembly reference?)	number_plate	c:\users\sohib\documents\visual studio 2015\Projects\number_plate\number_plate\Form1.cs

[![part of the code][3]][3]

I could only find AlprNet in my *D:\Projects\plate_recognition\openalpr-master\src\bindings\csharp\AlprNetTest* and it is in .csproj format.

AlprNet is not in .dll format like other references so I cannot reference it in References.
I found some say that it might be because of different versions of .NET Framework platforms. I almost did nothing to check that, because I don't think it's related to .NET

In my mere opinion I should link that AlprNet.csproj to get its content, but I'm not sure. If someone can help get around this issue, I'd be very grateful.

  [2]: https://www.youtube.com/watch?v=IjojAS0IPI4
  [3]: https://i.stack.imgur.com/JjN16.jpg

**Comment by PabloGh91** [comment]
I am now in exactly the same problem that you had. If you have managed to solve it, you would be as kind as to indicate how. Because I have tried the solution of Xtianhbpero, even though it keeps giving me errors that I can not solve.
![image](https://user-images.githubusercontent.com/46853607/57569952-caa0cf00-73fc-11e9-8d53-670968aae56c.png)

**Comment by efealigulocak** [comment]
Did you solve the problem ?

**Comment by xycisl** [comment]
I have the same error, have you resolved this error? can you please help me with it?
