### ISSUE TITLE
how to get infomation about number plate

### ISSUE THREAD

**Issue by mohit472** [openalpr/openalpr#727]
my alpr is working and giving me confidence 
let us 
`alpr lp.jpg`
it is giving me confidence 
after getting the confidence how to get information about the number plate 
and how to connect the system to live system through camera and capture images?
![screenshot from 2018-08-30 10-17-02](https://user-images.githubusercontent.com/25191880/44830143-e0d77800-ac3d-11e8-978e-7fabbe607f3b.png)

**Comment by zhouhao27** [comment]
Whatelse do you want to get? There are 10 results returned. The first vehicle number is 786P0. The confidence for this is 89.6593.

**Comment by mohit472** [comment]
I want to know that how can I connect through live cam as I am unable to connect it

**Comment by alvarogalia** [comment]
If you want to connect to a ip cammera you need to use openalpr daemon

**Comment by mohit472** [comment]
do u have any wiki or instructions how to use openalpr daemon to get live or real camera image

Also
Can we get information about the car
Like

> `like no is pb3457o`
`car is lambo 2017  model` something like that
2017 is model when the car is bought
And Lamborghini is the car name

**Comment by alvarogalia** [comment]
You have to write a Java/C++/Python app to get connected to ip camera (maybe with OpenCV) and send frame by frame to openalpr

**Comment by mohit472** [comment]
it is working with webcam
thank you
but I want to ask 
how to check number plate is real or fake?
`like the number is us2K766  and the number is fake`
`how can I check or allow the car to enter without knowing  the car exist or not`
you are getting my point.

all things are working but for that, I want to know only the car number exists or not.
because only for security purposes.

**Comment by alvarogalia** [comment]
If it doesn’t have a pattern, it’s hard to know if a plate number is fake or not

For example, in my country we have a pattern:
[A-Z][A-Z][A-Z][A-Z][0-9][0-9]

Any way the only way to know if the plate number isn’t fake is to view vehicle’s documents.
