### ISSUE TITLE
How to grab the position of the license plate? such as the [x,y,width,height]

### ISSUE THREAD

**Issue by eggeggss** [openalpr/openalpr#742]
hi ~ I try the python sample code,
but I only get the x,y but no width and height 
How to grab the position of the license plate? 
be like the bounding box

**Comment by MaudorElConquistador** [comment]
if you want draw a rectangle on the license plate, do it with the function of opencv cv.rectangle.
i did it like that.
`



        cor1x = json.dumps(x["results"][0]["coordinates"][0]["x"])
        cor1y = json.dumps(x["results"][0]["coordinates"][0]["y"])
        cor2x = json.dumps(x["results"][0]["coordinates"][2]["x"])
        cor2y = json.dumps(x["results"][0]["coordinates"][2]["y"])
        
        cv2.rectangle (img, (int(cor1x),int(cor1y)), (int(cor2x),int(cor2y)), (0,255,0), 3);
        `

**Comment by eggeggss** [comment]
thanks
