### ISSUE TITLE
Support of Malaysia car plates and car models?

### ISSUE THREAD

**Issue by jerrychong25** [openalpr/openalpr#790]
Hi,

May I know if openalpr now official supports recognition of Malaysian car plates and Malaysian car models?

Thanks.

**Comment by GTHell** [comment]
I think you need to train the alpr yourself. Refer to this [link](https://github.com/openalpr/train-ocr) for more about how to train your own OCR.
I'm from Cambodia and I find the US template just find 95% of the time. Maybe you can try different template from EU to US and see how it detect before trying to train your own OCR and recognition.

**Comment by jerrychong25** [comment]
> I think you need to train the alpr yourself. Refer to this [link](https://github.com/openalpr/train-ocr) for more about how to train your own OCR.
> I'm from Cambodia and I find the US template just find 95% of the time. Maybe you can try different template from EU to US and see how it detect before trying to train your own OCR and recognition.

Thanks for the advices. 

I will give it a try.

Just curious, how long do you took for training your own alpr?

**Comment by GTHell** [comment]
I've tried and give up. You need to gather a lot of data (license plate) for recognition and the OCR require specific font that uses by the license plate for training. None standardize fonts uses in license plate for your country and mine is the big reason that I think it's hard to train the OCR.

I've gather around 400-600 license plate in just one day (lurking around parking lots) but the process of extracting the font for OCR is tedious that I have to give up. But like I said, most of the cases, the US template serve its purpose. 9/10 detection will give me a satisfy result. I can only help you more if I know what project are you working on. 

Remember that if the US template can detect your license plate then there'll be 1 in 100 n that match the plate even if it show the confidence to be lower than the wrong one. If you're working on Parking system then take this 100 n of result to compare between checkin top 100n vs checkout 100n using some probability magic, you'll have a automatic parking system.

**Comment by jerrychong25** [comment]
> I've tried and give up. You need to gather a lot of data (license plate) for recognition and the OCR require specific font that uses by the license plate for training. None standardize fonts uses in license plate for your country and mine is the big reason that I think it's hard to train the OCR.
> 
> I've gather around 400-600 license plate in just one day (lurking around parking lots) but the process of extracting the font for OCR is tedious that I have to give up. But like I said, most of the cases, the US template serve its purpose. 9/10 detection will give me a satisfy result. I can only help you more if I know what project are you working on.
> 
> Remember that if the US template can detect your license plate then there'll be 1 in 100 n that match the plate even if it show the confidence to be lower than the wrong one. If you're working on Parking system then take this 100 n of result to compare between checkin top 100n vs checkout 100n using some probability magic, you'll have a automatic parking system.

Thanks for the advice.

Will look into it.

**Comment by alucard079** [comment]
@GTHell Did you know how do I improve the ocr of a plate? I'm also training my plate in OCR. but i'm encountering a problem, it looks like it's very hard to train this kind of plate number.

![ph_VDL-404](https://user-images.githubusercontent.com/28977709/54252017-3ba24280-4584-11e9-9d0d-077f1158f7e7.jpg)

**Comment by jerrychong25** [comment]
No longer using openalpr. Will close this issue.

Thanks all!
