### ISSUE TITLE
Odroid XU4 vs Raspberry Pi 3B

### ISSUE THREAD

**Issue by marcoslucianops** [openalpr/openalpr#799]
I have OpenALPR in my Rapsberry Pi 3 B but the performance is too slow. Is Odroid XU4 more powerful? How many percent approximately? The investment is worth?

**Comment by bodyweightenergy** [comment]
Around a year ago, I wrote a simple single producer-multiple consumer C++ program on my Odroid XU4. With 4 threads/workers (running on 4 cores), I managed to get ~3 FPS processing a 720p stream. While the XU4 has 8 CPU cores, only 4 of them are actually relatively powerful; the others are meant to handle light tasks such as IO. Unfortunately, I haven't saved that program anywhere so I can't share it.
