### ISSUE TITLE
error: package directory 'openalpr' does not exist

### ISSUE THREAD

**Issue by warpdriv** [openalpr/openalpr#806]
Hi, 

After downloading 2.3.0 of github and running python\setup.py install, I get the following error. I searched/read many articles trying to this working and would appreciate some help.

(licenseplate) C:\Users\somone\Downloads\openalpr-2.3.0-win-64bit\openalpr_64\python>python setup.py install
running install
running build
running build_py
error: package directory 'openalpr' does not exist

I'm on windows 10, anaconda, python 3.6.2 64-bit

Thank you.

**Comment by AT0myks** [comment]
I'm not familiar with anaconda but I got it working with just Python on Windows :
- add the openalpr_64 directory to the path (I put it in the user variables Path, from your example you should add `C:\Users\somone\Downloads\openalpr-2.3.0-win-64bit\openalpr_64`)
- restart the computer
- download the source code as a zip from [https://github.com/openalpr/openalpr/releases](url)
- unzip it somewhere
- run the same `python setup.py install` command but this time from `openalpr-2.3.0\src\bindings\python` it should work this time
Now you should be able to use openalpr from with python.

**Comment by warpdriv** [comment]
Thank you

**Comment by juskuz** [comment]
It allows to import openalpr in Python but for me it generates the next error:

`OSError: Unable to locate the OpenALPR library. Please make sure that OpenALPR is properly installed on your system and that the libraries are in the appropriate paths.
Exception ignored in: <bound method Alpr.__del__ of <openalpr.openalpr.Alpr object at 0x000001571BE136D8>>`

and:
`AttributeError: 'Alpr' object has no attribute 'loaded'`
