### ISSUE TITLE
Support for Sri Lankan Plates

### ISSUE THREAD

**Issue by RootAll** [openalpr/openalpr#853]
need help in training openalpr to recognize sri lanka plate.
Most plates belong to the below patterns:
WP	@@?####
WP	@@@?####
WP	@@?####
SP	@@?####
SP	@@@?####
SP	@@?####
CP	@@?####
CP	@@@?####
CP	@@?####
NW	@@?####
NW	@@@?####
NW	@@?####

**Comment by praveen-ravirathinam** [comment]
Do you need help with creating the patterns file or for the recognition process as a whole?

**Comment by RootAll** [comment]
Thanks for the reply @praveen-ravirathinam.
Really appreciate if you can help in the entire recognition process from patterns to ocr.

**Comment by praveen-ravirathinam** [comment]
So you will have to start by cropping out plates of your country one by one. You will have to collect single-line plates as well as multiline plates. 

OpenALPR detection works on the concept of Local Binary Patterns which is basically constructing histograms based on pixel values. So make sure the plates you collect are similar to the real scenario. 

Once you collect cropped out plates make sure you separate them as single-line and multiline line plates. You will need to make two separate detectors for one for detecting single-line plates and one for detecting multiline plates. The detector files are contained in XML files. The input for training the detector are the cropped out plates. An important thing to note is to resize all the plates to the same size. 

the program for training to get the detector XML file can be found here: https://github.com/openalpr/train-detector

I used dataturks.com for labeling and a python script to crop out the plates. use the above link to find the steps to get the XML file for detection. name it accordingly and add it to the correct place in the path

The next thing you will have to do is create a config file. this file is a text file and consists of general measurements on the plate. You can use my config files as a reference while constructing your file. after you finish typing this out add it to the path. 

OCR I did not train as the eu OCR worked well enough. 

Finally, you will have to create a patterns file. This is also a text file but save it as <countrycode>.patterns
the general format is @ for letters and # for numbers. Look at my patterns file for reference if needed. 
Add entries like @@##@@#### for single-line plates. 
and for the multiline patterns file like @@##\n@@#### where \n is where the next line starts.
Add the files to the path and you should be done!

Note that single line and multiline are completely different i.e you will need separate XML files, config files and patterns files for multiline as well as single line. I have implemented this for India and you can look at my repo for further details on file structure and format.

The hardest part of this whole process is the part of cropping out the plates. Rest all is pretty straight forward and in one week you should be good to go!

**Comment by RootAll** [comment]
@praveen-ravirathinam thank you very much for the support.
I had different size cropped plates that's the problem I think as you said.
Once again thank you!

**Comment by RootAll** [comment]
@praveen-ravirathinam thank you very much for the support.
I had different cropped plate sizes in my input as you said i think its the problem.
I'll try out your way and let you know its status.

once again thank you.

**Comment by praveen-ravirathinam** [comment]
@RootAll Sure no problem
All the best!!

**Comment by masgh21** [comment]
@praveen-ravirathinam 
for train arabic character , 
can you help me ??
how use it ??
