### ISSUE TITLE
Install without GPU support?

### ISSUE THREAD

**Issue by AGS-Knight** [openalpr/openalpr#86]
Is there a way to build without gpu/cuda support?

**Comment by matthill** [comment]
Does the GPU support make it harder for you to compile?  

You can get rid of it by deleting detectorcuda.cpp and detectorcuda.h and then removing DetectorCuda from the detectorfactory.cpp

**Comment by Silex** [comment]
@matthill: does the .deb come with GPU support built in? I'd like to test the performance when using CUDA/GPU but adding `gpu_mode=1` to the config seems to have no effect.

**Comment by AGS-Knight** [comment]
@matthill - I just typically build opencv without gpu support.  Ok, thanks - I'll try and build today.

**Comment by matthill** [comment]
I turned off GPU compilation in the default compile in commit 5e03e5b02fdb3898566a1f02fb64b7a24380bff8.  Please let me know if that helps.
