### ISSUE TITLE
OpenAlpr on server

### ISSUE THREAD

**Issue by ivanh23** [openalpr/openalpr#860]
Hello , i have script for licence plate recognition using opencv and openalpr , then i converted the script into exe file , got all libraries and uploaded them to windows server , and when i try to run the script error pops up : // OpenCL not detected OpenCV Error: Assertion failed (!empty()) in cv::CascadeClassifier::detectMultiScale, file C:\projects\openalpr-win\windows\opencv\modules\objdetect\src\cascadedetect.cpp, line 1634 Caught exception in OpenALPR recognize: C:\projects\openalpr-win\windows\opencv\modules\objdetect\src\cascadedetect.cpp:1634: error: (-215) !empty() in function cv::CascadeClassifier::detectMultiScale

Press any key to exit // This exe works on normal other PC without installed OpenCV or OpenAlpr can please someone help me

Plus this path is not on my pc : C:\projects\openalpr-win\windows\opencv\modules\objdetect\src\cascadedetect.cpp,

**Comment by brittosabu** [comment]
Same here

**Comment by brittosabu** [comment]
It is because, for the region which you are trying, you need to have "your_region.xml" file in the 
'openalpr_64/runtime_data/regions/' folder. 
I hope this will solve the problem.

**Comment by ivanh23** [comment]
Thank you for your answer ,but i managed to solve it , actually it was my stupid mistake , in the openalpr.conf, at:

; detector is the technique used to find license plate regions in an image.  Value can be set to
; lbpcpu    - default LBP-based detector uses the system CPU  
; lbpgpu    - LBP-based detector that uses Nvidia GPU to increase recognition speed.
; lbpopencl - LBP-based detector that uses OpenCL GPU to increase recognition speed.  Requires OpenCV 3.0
; morphcpu  - Experimental detector that detects white rectangles in an image.  Does not require training.
detector = lbpcpu   
i assigned lbpopencl detector , instead of CPU detector
