### ISSUE TITLE
Licence question

### ISSUE THREAD

**Issue by martijintro** [openalpr/openalpr#861]
We want to use your library (unmodified/original) in a commercial product. Because we don't modify it, we have no changes we want to hide. (e.g. due to a company secret)

Can we use your software if we provide a link to the original verison on this github site?

-> https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)

Thank you for your feedbacks.

Best regards from Switzerland,
Jan

**Comment by martijintro** [comment]
No answer??

**Comment by miclf** [comment]
As far as I know, no, you can’t. The GPL licence (and, by extension, the AGPL) make it mandatory to publish your stuff under the same terms. That’s actually the main purpose of the copyleft clause.
(that said, I’m not a lawyer)

**Comment by miclf** [comment]
@martijintro [This page](http://doc.openalpr.com/opensource.html#commercial-enhancements) in the docs should answer your questions.

**Comment by martijintro** [comment]
Thank you very much for your feedback!

**Comment by martijintro** [comment]
Closed

**Comment by martijintro** [comment]
I think it's a product strategy to make the opensource version completely unusable, so the people buy it because they are resignated.

I think i'm right with that.

So the OS version is just a decoy, nothing else....!!

And i don't like that strategy. Because it's not honest.

Because of that, now i try it with https://platerecognizer.com, hehe!! :-)
