### ISSUE TITLE
Are OpenALPR version 2.3.109 and above open source?

### ISSUE THREAD

**Issue by GhettoBurger996** [openalpr/openalpr#864]
Hey all, 

Was just wondering if version 2.3.109 and above (particularly 2.6.103, since I need the Malaysian and Singaporean data-set) are free.

Could not find any information regarding this, and if it is free how do I go about updating the API. Currently on this repos latest release (OpenALPR 2.3.0). 

Thanks!

**Comment by CYbooN** [comment]
Hi, are you still working for Malaysia and Singapore license plate?

**Comment by GhettoBurger996** [comment]
yep, mainly focusing towards the Malaysia license plate at the moment though.

**Comment by CYbooN** [comment]
> yep, mainly focusing towards the Malaysia license plate at the moment though.

Hi, are you malaysian? Actually, now i am working on Malaysia license plate, maybe we can share the plate datasets?

**Comment by GhettoBurger996** [comment]
sure if you have a Discord account @CYbooN  drop me a message on my discord GhettoBurger #5807
