### ISSUE TITLE
question about licence model

### ISSUE THREAD

**Issue by martijintro** [openalpr/openalpr#879]
**Is your software i can download from github completely opensource?**

**If yes:** Is it able to detect licence plates by itself, which means without any network connection to cloud, server, etc?

**If yes:** If it's completely opensource, why i can enter some licence keys?

**If no:** Are parts of your software i can download from github closed-source?

**Comment by jmar83** [comment]
Here i read something about a "open source" vs. "commercial" agent:
http://doc.openalpr.com/alprd.html

Now i downloaded the win64 version here on github, but there is not file called `alprd.conf` - only `openalpr.conf`... but it doesn't have a section `[daemon]` for example...

So: How to start and configure the opensource agent after unpacking that zip?
-> https://github.com/openalpr/openalpr/releases/download/v2.3.0/openalpr-2.3.0-win-64bit.zip

And there is also nothing called "alprd" or similar...

Thank you for your feedback.


Best regards,
Jan

**Comment by martijintro** [comment]
I think it's a product strategy to make the opensource version completely unusable, so the people buy it because they are resignated.

I think i'm right with that.


So the OS version is just a decoy, nothing else....!!

And i don't like that strategy. Because it's not honest.

Because of that, now i try it with https://platerecognizer.com, hehe!! :-)
