### ISSUE TITLE
Country config file does not exist?

### ISSUE THREAD

**Issue by martijintro** [openalpr/openalpr#881]
```
alpr -c CH test.jpeg
--(!) Country config file '/usr/share/openalpr/runtime_data/config/CH.conf' does not exist.  Missing config for the country: 'CH'!

```

why??

**Comment by maechler** [comment]
I have never received an answer whether I should include the Swiss license plate data into the EU traineddata or whether there should be a separate Switzerland only configuration. That is why at the moment there is no `ch.conf`, anyone looking for the configuration necessary, please look here: https://github.com/openalpr/train-ocr/issues/34#issuecomment-609913141

**Comment by martijintro** [comment]
ok thx!

**Comment by martijintro** [comment]
I think it's a product strategy to make the opensource version completely unusable, so the people buy it because they are resignated.

I think i'm right with that.

So the OS version is just a decoy, nothing else....!!

And i don't like that strategy. Because it's not honest.

Because of that, now i try it with https://platerecognizer.com, hehe!! :-)
