### ISSUE TITLE
training data in /usr/share/openalpr/runtime_data/ocr/ or /usr/share/openalpr/runtime_data/ocr/tessdata

### ISSUE THREAD

**Issue by martijintro** [openalpr/openalpr#882]
Message:

```
alpr -c eu test.jpg
Error opening data file /usr/share/openalpr/runtime_data/ocr/leu.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'leu'
Tesseract couldn't load any languages!
```

Then:

```
TESSDATA_PREFIX=/usr/share/openalpr/runtime_data/ocr/tessdata
```

After that, same message:

```
alpr -c eu test.jpg
Error opening data file /usr/share/openalpr/runtime_data/ocr/leu.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'leu'
Tesseract couldn't load any languages!

```

Why the files are in /usr/share/openalpr/runtime_data/ocr/tessdata, but the alpr searches for it on /usr/share/openalpr/runtime_data/ocr? And why it does not work to set the `TESSDATA_PREFIX` variable?

When i set that variable to /usr/share/openalpr/runtime_data/ocr/tessdata, the aplr app still searches in  /usr/share/openalpr/runtime_data/ocr for it...

why??

thanks for feedback,.

**Comment by martijintro** [comment]
May i should soft-link all files from `/usr/share/openalpr/runtime_data/ocr/tessdata` to `/usr/share/openalpr/runtime_data/ocr` ???

**Comment by martijintro** [comment]
Now i suddenly get an memory access error:

```
alpr n.jpg
Error opening data file /usr/share/openalpr/runtime_data/ocr/lus.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'lus'
Tesseract couldn't load any languages!
Speicherzugriffsfehler (Speicherabzug geschrieben)

```

**Comment by martijintro** [comment]
noibody knows about the directory problem`??

**Comment by martijintro** [comment]
same problem with that command, WTF?!?!

`TESSDATA_PREFIX=/usr/share/openalpr/runtime_data/ocr/tessdata && alpr n.jpg`

**Comment by martijintro** [comment]
Maybe that bug is only on the version i've downloaded from the ubuntu APT repo?!?!

**Comment by martijintro** [comment]
https://debianforum.de/forum/viewtopic.php?f=27&t=176976&p=1234596#p1234596

**Comment by martijintro** [comment]
question seems to be too complex or what??

**Comment by martijintro** [comment]
I think it's a product strategy to make the opensource version completely unusable, so the people buy it because they are resignated.

I think i'm right with that.


So the OS version is just a decoy, nothing else....!!

And i don't like that strategy. Because it's not honest.

Because of that, now i try it with https://platerecognizer.com, hehe!! :-)

**Comment by theonlyNischal** [comment]
`sudo cp -a /usr/share/openalpr/runtime_data/ocr/tessdata/*.traineddata /usr/share/openalpr/runtime_data/ocr/`

I had the same issue and copying solved my issue.

**Comment by martijintro** [comment]
Thank you for your information.

Since we use Debian 9.x, instead of Ubuntu 18.x LTS, the problem does not exist anymore. On Debian 9.x, it's not necessary to solve that issue - works by default without that problems.
