### ISSUE TITLE
Does it work with Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by jayjupdhig** [openalpr/openalpr#910]
Hi there

Does the current version work with Ubuntu 20.04 LTS?

Thank you for your feedback.

With best regards,
Jan

**Comment by jayjupdhig** [comment]
No answer?!?

**Comment by marknguy** [comment]
yes, it worked for me.

**Comment by jayjupdhig** [comment]
ok thx

**Comment by tkhan3** [comment]
@marknguy seems ubuntu installable is not present. Did you complied it via source ?

**Comment by jayjupdhig** [comment]
Answser is too late - not interested anymore...

**Comment by jayjupdhig** [comment]
unsubscribed!! ;-)
