### ISSUE TITLE
Identify state by comparing color (HSV) histogram cross sections

### ISSUE THREAD

**Issue by matthill** [openalpr/openalpr#96]
Given a color image of a plate, separate it into 3 strips:

  - Plate characters
  - Top of plate
  - Bottom of plate

For each strip, generate an HSV histogram.  Run a comparison against the Hue and Saturation values to a known plate image
http://docs.opencv.org/doc/tutorials/imgproc/histograms/histogram_comparison/histogram_comparison.html

This would produce a likeness score based on the colors used on the plate.  For example, Michigan is unique because all three strips are vivid blue:
http://www.plateshack.com/y2k/Michigan2/mi2012.jpg

This score can be combined with other analyses (e.g., character font analysis, 2d feature detection) to form an accurate estimate for the locality of the plate.

**Comment by vielmetti** [comment]
Specific to Michigan, there are actually a variety of current plate colors; the blue is the older plate, the new ones have various designs (that should be recognizable as well).

https://www.michigan.gov/sos/0,4670,7-127-1585_1595_1607---,00.html

**Comment by matthill** [comment]
Solved in OpenALPR commercial
